// CodeQuest - CSS Learning Content
// Curso completo em Português com módulos bem categorizados

import { LearningModule, Lesson, QuizQuestion } from './lessons';

// ============================================
// MÓDULO 1: FUNDAMENTOS CSS
// ============================================

export const CSS_FUNDAMENTOS: LearningModule = {
    id: 'css-fundamentos',
    name: 'Fundamentos CSS',
    description: 'Aprenda a base do CSS: sintaxe, seletores e como aplicar estilos',
    icon: '🎨',
    difficulty: 'beginner',
    lessons: [
        {
            id: 'intro-css',
            title: 'Introdução ao CSS',
            description: 'O que é CSS, como funciona e por que é essencial para web',
            xpReward: 150,
            estimatedTime: 25,
            content: {
                introduction: 'CSS (Cascading Style Sheets) é a linguagem que dá vida visual às páginas web. Enquanto HTML define a estrutura e o conteúdo, CSS controla toda a aparência: cores, fontes, espaçamentos, layouts e animações. Junto com HTML e JavaScript, CSS forma a base do desenvolvimento front-end moderno. Toda página web que você visita usa CSS.',
                sections: [
                    {
                        title: 'O que é CSS?',
                        text: 'CSS significa Cascading Style Sheets (Folhas de Estilo em Cascata). É a linguagem que descreve como os elementos HTML devem ser exibidos na tela. Com CSS você pode controlar cores, fontes, espaçamentos, layouts, animações e criar designs responsivos que se adaptam a diferentes dispositivos.',
                        code: '/* Exemplo básico de CSS */\nbody {\n  background-color: #f5f5f5;\n  font-family: Arial, sans-serif;\n}\n\nh1 {\n  color: #333;\n  text-align: center;\n}\n\np {\n  line-height: 1.6;\n  margin: 20px;\n}',
                    },
                    {
                        title: 'Por que usar CSS?',
                        text: 'CSS separa o conteúdo (HTML) da apresentação visual, trazendo várias vantagens: reutilização de estilos em múltiplas páginas, mudanças globais com uma única alteração, código mais organizado e fácil de manter, layouts responsivos para todos os dispositivos, e páginas mais rápidas (CSS é cacheado).',
                        code: '/* Um arquivo CSS pode estilizar todo o site */\n/* styles.css */\n\n/* Estilos globais */\n* {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}\n\n/* Tipografia do site inteiro */\nbody {\n  font-family: "Segoe UI", sans-serif;\n  font-size: 16px;\n  color: #333;\n}\n\n/* Todos os links do site */\na {\n  color: #0066cc;\n  text-decoration: none;\n}',
                    },
                    {
                        title: 'CSS Externo (Recomendado)',
                        text: 'O método mais usado é criar um arquivo .css separado e vinculá-lo ao HTML com a tag <link>. Isso permite reutilizar os mesmos estilos em várias páginas, facilita manutenção e permite cache pelo navegador (páginas carregam mais rápido).',
                        code: '<!-- index.html -->\n<!DOCTYPE html>\n<html>\n<head>\n  <title>Meu Site</title>\n  <!-- Vinculando CSS externo -->\n  <link rel="stylesheet" href="css/styles.css">\n  <link rel="stylesheet" href="css/responsive.css">\n</head>\n<body>\n  <h1>Olá Mundo!</h1>\n</body>\n</html>\n\n/* css/styles.css */\nh1 {\n  color: navy;\n  font-size: 2rem;\n}',
                    },
                    {
                        title: 'CSS Interno e Inline',
                        text: 'CSS interno usa a tag <style> no head - útil para estilos únicos de uma página. CSS inline usa o atributo style diretamente no elemento - evite pois mistura estrutura com estilo. Use inline apenas para testes rápidos ou estilos dinâmicos via JavaScript.',
                        code: '<!-- CSS Interno (no head) -->\n<head>\n  <style>\n    .destaque {\n      background: yellow;\n      padding: 10px;\n    }\n  </style>\n</head>\n\n<!-- CSS Inline (evite!) -->\n<p style="color: red; font-size: 18px;">Texto vermelho</p>\n\n<!-- Melhor: use classes -->\n<p class="texto-erro">Texto vermelho</p>',
                    },
                    {
                        title: 'Cascata e Herança',
                        text: 'O "Cascading" em CSS significa que estilos podem ser herdados de elementos pai e sobrepostos. Elementos filhos herdam certas propriedades (como color e font). Quando há conflito, a regra mais específica ou a última declarada vence.',
                        code: '/* Herança: filhos herdam estilos do pai */\nbody {\n  font-family: Arial;  /* todos elementos herdam */\n  color: #333;         /* todos textos ficam cinza */\n}\n\n/* Cascata: última regra vence (com mesma especificidade) */\np {\n  color: blue;\n}\np {\n  color: red;  /* Esta vence! */\n}\n\n/* Herança pode ser explícita */\n.container {\n  border: 1px solid black;\n}\n.item {\n  border: inherit;  /* herda borda do pai */\n}',
                    },
                    {
                        title: 'Especificidade CSS',
                        text: 'Quando múltiplas regras se aplicam ao mesmo elemento, CSS usa especificidade para decidir qual aplicar. A ordem (menor para maior): elementos (1) < classes (10) < ID (100) < inline (1000) < !important. Evite !important - indica problema no código.',
                        code: '/* Especificidade em ordem crescente */\np { color: black; }           /* 1 ponto */\n.texto { color: blue; }        /* 10 pontos */\n#principal { color: green; }   /* 100 pontos */\n/* inline style = 1000 pontos */\n\n/* Combinações somam */\ndiv p { }                      /* 2 pontos */\ndiv.container p.texto { }     /* 22 pontos */\n#main .content p { }          /* 112 pontos */\n\n/* !important vence tudo (evite!) */\np {\n  color: red !important;  /* vence qualquer outra regra */\n}',
                    },
                    {
                        title: 'Sintaxe Básica CSS',
                        text: 'Uma regra CSS tem: seletor (o que estilizar), propriedade (o que mudar) e valor (como mudar). Múltiplas propriedades ficam dentro de chaves {}. Cada declaração termina com ponto e vírgula. Comentários usam /* */.',
                        code: '/* Anatomia de uma regra CSS */\nseletor {\n  propriedade: valor;\n  propriedade2: valor2;\n}\n\n/* Exemplo real */\n.botao {\n  /* Cores */\n  background-color: #3498db;\n  color: white;\n  \n  /* Espaçamento */\n  padding: 12px 24px;\n  margin: 10px;\n  \n  /* Bordas */\n  border: none;\n  border-radius: 5px;\n  \n  /* Tipografia */\n  font-size: 16px;\n  font-weight: bold;\n}',
                    },
                    {
                        title: 'Organizando seu CSS',
                        text: 'Boas práticas para organizar CSS: agrupe regras relacionadas, use comentários para separar seções, siga uma ordem consistente de propriedades (posicionamento > display > box model > visual > texto), e considere metodologias como BEM para projetos grandes.',
                        code: '/* ========================================\n   RESET / BASE\n   ======================================== */\n* {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}\n\n/* ========================================\n   LAYOUT\n   ======================================== */\n.container {\n  max-width: 1200px;\n  margin: 0 auto;\n  padding: 20px;\n}\n\n/* ========================================\n   COMPONENTES\n   ======================================== */\n.card {\n  /* Posicionamento */\n  position: relative;\n  \n  /* Box Model */\n  padding: 20px;\n  margin-bottom: 20px;\n  \n  /* Visual */\n  background: white;\n  border-radius: 8px;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}',
                    },
                ],
                tips: [
                    'Sempre use CSS externo para projetos reais',
                    'Evite !important - indica problema de especificidade',
                    'Organize CSS em seções com comentários',
                    'Use classes em vez de IDs para estilização',
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'O que significa CSS?',
                    options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System', 'Colorful Style Sheets'],
                    correctAnswer: 0,
                    explanation: 'CSS significa Cascading Style Sheets (Folhas de Estilo em Cascata)',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Qual método de CSS é mais recomendado para projetos?',
                    options: ['Inline', 'Interno', 'Externo', 'Todos são iguais'],
                    correctAnswer: 2,
                    explanation: 'CSS externo (arquivo .css) é o mais recomendado por separar estrutura de estilo',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'multiple-choice',
                    question: 'Qual tag é usada para vincular um arquivo CSS externo?',
                    options: ['<style>', '<css>', '<link>', '<stylesheet>'],
                    correctAnswer: 2,
                    explanation: 'A tag <link> com rel="stylesheet" vincula arquivos CSS externos',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'CSS inline tem maior prioridade que CSS externo',
                    correctAnswer: 'true',
                    explanation: 'CSS inline tem a maior especificidade, sobrepondo estilos externos',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'fill-blank',
                    question: 'Complete: <link rel="____" href="styles.css">',
                    correctAnswer: 'stylesheet',
                    explanation: 'O atributo rel="stylesheet" indica que o arquivo é uma folha de estilos',
                    points: 15,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Onde a tag <link> para CSS deve ser colocada?',
                    options: ['No <body>', 'No <head>', 'Antes do DOCTYPE', 'Após o </html>'],
                    correctAnswer: 1,
                    explanation: 'A tag <link> deve ficar no <head> para carregar estilos antes do conteúdo',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'true-false',
                    question: 'CSS pode alterar o conteúdo do HTML',
                    correctAnswer: 'false',
                    explanation: 'CSS altera apenas a aparência. Para mudar conteúdo, use JavaScript',
                    points: 10,
                },
                {
                    id: 'q8',
                    type: 'multiple-choice',
                    question: 'Qual é a ordem de especificidade CSS (menor para maior)?',
                    options: ['Inline > ID > Classe > Elemento', 'Elemento > Classe > ID > Inline', 'ID > Inline > Classe > Elemento', 'Classe > Elemento > Inline > ID'],
                    correctAnswer: 1,
                    explanation: 'A ordem é: Elemento < Classe < ID < Inline (inline tem maior prioridade)',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'fill-blank',
                    question: 'Para CSS interno, usamos a tag <____> dentro do head',
                    correctAnswer: 'style',
                    explanation: 'A tag <style> contém CSS interno no documento HTML',
                    points: 15,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'Qual vantagem do CSS externo sobre o inline?',
                    options: ['É mais rápido sempre', 'Pode ser reutilizado em múltiplas páginas', 'Tem maior especificidade', 'Não precisa de conexão'],
                    correctAnswer: 1,
                    explanation: 'CSS externo pode ser compartilhado entre páginas, facilitando manutenção',
                    points: 10,
                },
            ],
        },

        {
            id: 'sintaxe-css',
            title: 'Sintaxe CSS',
            description: 'Aprenda a estrutura de regras CSS: seletores, propriedades e valores',
            xpReward: 100,
            estimatedTime: 15,
            content: {
                introduction: 'Uma regra CSS é composta por seletor, propriedade e valor. A sintaxe é simples mas poderosa. Dominar os conceitos de unidades, shorthand e variáveis CSS vai tornar seu código mais eficiente e fácil de manter.',
                sections: [
                    {
                        title: 'Estrutura de uma Regra CSS',
                        text: 'Uma regra CSS tem três partes: Seletor (qual elemento), Propriedade (o que mudar) e Valor (como mudar). Múltiplas declarações são separadas por ponto e vírgula.',
                        code: '/* Estrutura básica */\nseletor {\n  propriedade: valor;\n}\n\n/* Exemplo prático */\np {\n  color: blue;\n  font-size: 16px;\n  line-height: 1.5;\n}\n\n/* Múltiplos seletores */\nh1, h2, h3 {\n  font-family: Arial, sans-serif;\n  color: #333;\n}',
                    },
                    {
                        title: 'Unidades de Medida',
                        text: 'CSS tem unidades absolutas (px, pt) e relativas (em, rem, %, vh, vw). Unidades relativas escalam melhor. rem é baseado no font-size root, em é baseado no elemento pai.',
                        code: '/* Unidades absolutas */\n.box {\n  width: 300px;      /* pixels */\n  border: 2pt solid; /* pontos */\n}\n\n/* Unidades relativas */\n.container {\n  width: 100%;       /* porcentagem do pai */\n  max-width: 1200px;\n  height: 100vh;     /* viewport height */\n  padding: 1rem;     /* relativo ao root */\n  margin: 2em;       /* relativo ao font-size do elemento */\n}\n\n/* Comparação rem vs em */\nhtml { font-size: 16px; } /* base */\n.texto { font-size: 1rem; } /* 16px sempre */\n.aninhado { font-size: 1.5em; } /* 150% do pai */\n\n/* Viewport units */\n.hero {\n  height: 100vh;  /* altura da viewport */\n  width: 50vw;    /* metade da largura */\n}',
                    },
                    {
                        title: 'Shorthand Properties',
                        text: 'Shorthand combina múltiplas propriedades relacionadas em uma só. margin, padding, border, font e background têm versões shorthand. Cuidado: shorthand reseta valores não especificados!',
                        code: '/* Longhand (individual) */\n.box {\n  margin-top: 10px;\n  margin-right: 20px;\n  margin-bottom: 10px;\n  margin-left: 20px;\n}\n\n/* Shorthand - 4 valores: top right bottom left */\n.box {\n  margin: 10px 20px 10px 20px;\n}\n\n/* Shorthand - 2 valores: vertical horizontal */\n.box {\n  margin: 10px 20px;\n  padding: 15px 30px;\n}\n\n/* Shorthand - 1 valor: todos iguais */\n.box {\n  margin: 20px;\n}\n\n/* Font shorthand */\n.texto {\n  font: italic bold 16px/1.5 Arial, sans-serif;\n  /* style weight size/line-height family */\n}\n\n/* Background shorthand */\n.hero {\n  background: url("img.jpg") center/cover no-repeat;\n}',
                    },
                    {
                        title: 'Variáveis CSS (Custom Properties)',
                        text: 'Variáveis CSS permitem reutilizar valores. Declare com -- e use com var(). Geralmente definidas em :root para acesso global. Facilitam manutenção e temas.',
                        code: '/* Definindo variáveis globais */\n:root {\n  --cor-primaria: #3498db;\n  --cor-secundaria: #2ecc71;\n  --espacamento: 16px;\n  --fonte-principal: Arial, sans-serif;\n}\n\n/* Usando variáveis */\n.botao {\n  background-color: var(--cor-primaria);\n  padding: var(--espacamento);\n  font-family: var(--fonte-principal);\n}\n\n.botao:hover {\n  background-color: var(--cor-secundaria);\n}\n\n/* Valor fallback */\n.card {\n  color: var(--cor-texto, #333); /* usa #333 se não existir */\n}\n\n/* Tema escuro */\n.dark-theme {\n  --cor-primaria: #1a1a2e;\n  --cor-secundaria: #4a4a6a;\n}',
                    },
                    {
                        title: 'Comentários e Organização',
                        text: 'Use comentários /* */ para documentar e organizar. Agrupe regras relacionadas em seções. Uma boa organização evita duplicação e facilita manutenção.',
                        code: '/* ================================\n   RESET E BASE\n   ================================ */\n* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}\n\n/* ================================\n   TIPOGRAFIA\n   ================================ */\nbody {\n  font-family: var(--fonte-principal);\n  font-size: 16px;\n}\n\nh1 { font-size: 2rem; }\nh2 { font-size: 1.5rem; }\n\n/* ================================\n   COMPONENTES\n   ================================ */\n/* Botões */\n.btn { /* ... */ }\n.btn-primary { /* ... */ }\n\n/* Cards */\n.card { /* ... */ }',
                    },
                    {
                        title: '!important e Especificidade',
                        text: '!important força uma regra a ter prioridade máxima. Use com MUITA cautela - dificulta manutenção. Prefira aumentar especificidade do seletor ou reorganizar o CSS.',
                        code: '/* !important sobrescreve tudo */\n.texto {\n  color: blue !important; /* sempre azul */\n}\n\n/* Problemas do !important */\n.texto { color: red; } /* ignorado */\n.texto.destaque { color: green; } /* ignorado */\n#id .texto { color: purple; } /* ignorado */\n\n/* ❌ Evite guerras de !important */\n.classe { color: blue !important; }\n.outra { color: red !important; } /* qual ganha? */\n\n/* ✅ Melhor: ajustar especificidade */\n.container .texto.destaque {\n  color: red; /* mais específico, sem !important */\n}\n\n/* Quando usar !important:\n   - Sobrescrever CSS de bibliotecas\n   - Utilitários (ex: .hidden { display: none !important; })\n   - Em último caso, temporariamente */\n',
                    },
                    {
                        title: 'Boas Práticas de Formatação',
                        text: 'CSS legível é fácil de manter. Uma propriedade por linha, indentação consistente, espaços organizados. Ferramentas como Prettier formatam automaticamente.',
                        code: '/* ❌ Difícil de ler */\n.btn{color:red;padding:10px;margin:5px;border:none;background:blue;}\n\n/* ✅ Formatação clara */\n.btn {\n  color: red;\n  padding: 10px;\n  margin: 5px;\n  border: none;\n  background: blue;\n}\n\n/* Ordem recomendada de propriedades */\n.elemento {\n  /* Posicionamento */\n  position: relative;\n  top: 0;\n  \n  /* Display e Box Model */\n  display: flex;\n  width: 100%;\n  padding: 1rem;\n  margin: 0;\n  \n  /* Cores e Visual */\n  background: #fff;\n  color: #333;\n  border: 1px solid #ddd;\n  \n  /* Tipografia */\n  font-size: 1rem;\n  line-height: 1.5;\n  \n  /* Outros */\n  cursor: pointer;\n  transition: all 0.3s;\n}',
                    },
                ],
                tips: [
                    'Use rem para fontes e px para bordas',
                    'Variáveis CSS facilitam temas e manutenção',
                    'Evite !important - ajuste especificidade',
                    'Shorthand reseta valores não especificados',
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual é a sintaxe correta de uma regra CSS?',
                    options: ['seletor { propriedade: valor; }', 'seletor (propriedade = valor)', 'seletor: propriedade, valor', '{seletor} propriedade: valor'],
                    correctAnswer: 0,
                    explanation: 'A sintaxe correta usa chaves {} e dois pontos : para separar propriedade do valor',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Como se faz um comentário em CSS?',
                    options: ['// comentário', '<!-- comentário -->', '/* comentário */', '# comentário'],
                    correctAnswer: 2,
                    explanation: 'Comentários CSS usam /* para abrir e */ para fechar',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'true-false',
                    question: 'O ponto e vírgula (;) é obrigatório após cada declaração CSS',
                    correctAnswer: 'true',
                    explanation: 'O ponto e vírgula separa declarações e é necessário (exceto na última)',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'fill-blank',
                    question: 'Complete: p { color: ____; }',
                    correctAnswer: 'blue',
                    explanation: 'O valor define a cor do texto, neste caso "blue" (azul)',
                    points: 15,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Em "h1 { font-size: 24px; }", qual é a propriedade?',
                    options: ['h1', 'font-size', '24px', 'px'],
                    correctAnswer: 1,
                    explanation: 'font-size é a propriedade que define o tamanho da fonte',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Em "h1 { font-size: 24px; }", qual é o seletor?',
                    options: ['h1', 'font-size', '24px', '{ }'],
                    correctAnswer: 0,
                    explanation: 'h1 é o seletor - define qual elemento será estilizado',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'fill-blank',
                    question: 'Complete: div { background____color: red; }',
                    correctAnswer: '-',
                    explanation: 'Propriedades compostas usam hífen: background-color',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'true-false',
                    question: 'CSS é case-sensitive para nomes de propriedades',
                    correctAnswer: 'false',
                    explanation: 'CSS não diferencia maiúsculas de minúsculas para propriedades',
                    points: 10,
                },
                {
                    id: 'q9',
                    type: 'multiple-choice',
                    question: 'Quantas propriedades pode ter uma regra CSS?',
                    options: ['Apenas 1', 'Máximo 10', 'Ilimitadas', 'Máximo 50'],
                    correctAnswer: 2,
                    explanation: 'Uma regra CSS pode ter quantas propriedades forem necessárias',
                    points: 10,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'O que acontece se esquecer o ponto e vírgula?',
                    options: ['Nada', 'Erro de sintaxe', 'As propriedades seguintes podem não funcionar', 'O navegador corrige automaticamente'],
                    correctAnswer: 2,
                    explanation: 'Sem ; o navegador pode interpretar errado as próximas declarações',
                    points: 15,
                },
            ],
        },

        {
            id: 'seletores-css',
            title: 'Seletores CSS',
            description: 'Domine os diferentes tipos de seletores para selecionar elementos',
            xpReward: 120,
            estimatedTime: 20,
            content: {
                introduction: 'Seletores determinam quais elementos HTML serão estilizados. Dominar seletores é crucial para CSS eficiente - você pode selecionar elementos específicos sem modificar HTML. De seletores simples a pseudo-classes e combinadores, vamos explorar todo o poder dos seletores.',
                sections: [
                    {
                        title: 'Seletores Básicos',
                        text: 'Os três seletores fundamentais: elemento (tag), classe (.) e ID (#). Elemento seleciona todos de um tipo, classe é reutilizável, ID é único. Classes são preferidas para estilização.',
                        code: '/* Seletor de elemento - todos os p */\np {\n  color: #333;\n  line-height: 1.6;\n}\n\n/* Seletor de classe - reutilizável */\n.destaque {\n  background-color: yellow;\n  padding: 0.5rem;\n}\n\n/* Seletor de ID - único na página */\n#cabecalho {\n  background: #1a1a2e;\n  color: white;\n}\n\n/* Seletor universal - todos os elementos */\n* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}',
                    },
                    {
                        title: 'Combinadores',
                        text: 'Combinadores definem relações entre elementos. Descendente (espaço), filho direto (>), irmão adjacente (+), irmãos gerais (~). Cada um tem uso específico.',
                        code: '/* Descendente - qualquer p dentro de div */\ndiv p { color: blue; }\n\n/* Filho direto - só p filho imediato de div */\ndiv > p { color: red; }\n\n/* Irmão adjacente - p logo após h1 */\nh1 + p { font-size: 1.2rem; }\n\n/* Irmãos gerais - todos p após h1 */\nh1 ~ p { color: gray; }\n\n/* Exemplo prático */\n<div>\n  <p>Filho direto</p>  /* div > p: sim */\n  <section>\n    <p>Neto</p>  /* div p: sim, div > p: não */\n  </section>\n</div>',
                    },
                    {
                        title: 'Agrupando e Combinando',
                        text: 'Agrupe seletores com vírgula para aplicar mesmas regras. Combine seletores (sem espaço) para maior especificidade. Ambos reduzem repetição de código.',
                        code: '/* Agrupando - mesmas regras para vários */\nh1, h2, h3, h4 {\n  font-family: "Roboto", sans-serif;\n  color: #222;\n}\n\n/* Combinando - p com classe intro */\np.intro {\n  font-size: 1.25rem;\n  font-weight: bold;\n}\n\n/* Elemento com múltiplas classes */\n.btn.btn-large.btn-primary {\n  /* elemento tem TODAS as classes */\n}\n\n/* ID + classe (raro mas válido) */\n#menu.aberto {\n  display: block;\n}\n\n/* Encadeamento complexo */\nnav.main-nav > ul > li.active > a {\n  color: var(--cor-primaria);\n}',
                    },
                    {
                        title: 'Pseudo-classes de Estado',
                        text: 'Pseudo-classes selecionam elementos em estados específicos. :hover (mouse sobre), :focus (focado), :active (clicando), :visited (link visitado). Essenciais para interatividade.',
                        code: '/* Mouse sobre elemento */\na:hover {\n  color: red;\n  text-decoration: underline;\n}\n\n/* Elemento focado (teclado/tab) */\ninput:focus {\n  border-color: blue;\n  outline: 2px solid lightblue;\n}\n\n/* Sendo clicado */\nbutton:active {\n  transform: scale(0.98);\n}\n\n/* Link visitado */\na:visited {\n  color: purple;\n}\n\n/* Desabilitado */\ninput:disabled {\n  opacity: 0.5;\n  cursor: not-allowed;\n}\n\n/* Checkbox marcado */\ninput:checked + label {\n  font-weight: bold;\n}',
                    },
                    {
                        title: 'Pseudo-classes Estruturais',
                        text: ':first-child, :last-child, :nth-child() selecionam por posição. :nth-child(odd/even) para zebrado. :not() para exclusão. Muito úteis para listas e tabelas.',
                        code: '/* Primeiro e último filho */\nli:first-child { border-top: none; }\nli:last-child { border-bottom: none; }\n\n/* Por posição */\nli:nth-child(2) { /* segundo item */ }\nli:nth-child(3n) { /* cada terceiro: 3, 6, 9... */ }\n\n/* Pares e ímpares (zebrado) */\ntr:nth-child(odd) { background: #f5f5f5; }\ntr:nth-child(even) { background: #fff; }\n\n/* Fórmula: an+b */\nli:nth-child(2n+1) { /* 1, 3, 5... (ímpares) */ }\nli:nth-child(3n+2) { /* 2, 5, 8, 11... */ }\n\n/* Negação */\np:not(.intro) { /* todos p EXCETO .intro */ }\na:not([href^="http"]) { /* links internos */ }',
                    },
                    {
                        title: 'Pseudo-elementos',
                        text: 'Pseudo-elementos (::) criam "elementos virtuais" para estilizar partes. ::before e ::after inserem conteúdo. ::first-line e ::first-letter para tipografia. Sempre use ::, não :.',
                        code: '/* Inserir conteúdo antes/depois */\n.icone::before {\n  content: "★";\n  margin-right: 0.5rem;\n}\n\nblockquote::before,\nblockquote::after {\n  content: \\"\\";\n  font-size: 2rem;\n}\n\n/* Decorações */\n.link::after {\n  content: " →";\n}\n\n/* Primeira letra grande (drop cap) */\np::first-letter {\n  font-size: 3rem;\n  float: left;\n  line-height: 1;\n}\n\n/* Primeira linha */\np::first-line {\n  font-weight: bold;\n}\n\n/* Seleção de texto */\n::selection {\n  background: yellow;\n  color: black;\n}',
                    },
                    {
                        title: 'Seletores de Atributo',
                        text: 'Selecione por atributos HTML: [attr] (existe), [attr="valor"] (exato), [attr^=""] (começa), [attr$=""] (termina), [attr*=""] (contém). Poderosos para formulários e links.',
                        code: '/* Tem atributo */\ninput[required] {\n  border-left: 3px solid red;\n}\n\n/* Valor exato */\ninput[type="email"] {\n  background: url("email-icon.svg") no-repeat right;\n}\n\n/* Começa com */\na[href^="https://"] {\n  /* links externos HTTPS */\n}\n\na[href^="mailto:"] {\n  /* links de email */\n}\n\n/* Termina com */\na[href$=".pdf"] {\n  /* links para PDFs */\n}\n\n/* Contém */\na[href*="youtube"] {\n  /* links para YouTube */\n}\n\n/* Case insensitive */\nimg[alt*="logo" i] {\n  /* i = ignora maiúsculas */\n}',
                    },
                    {
                        title: 'Especificidade e Prioridade',
                        text: 'Quando múltiplas regras conflitam, especificidade decide: inline > ID > classe > elemento. Conte como (0,0,0,0): IDs, classes, elementos. Maior vence.',
                        code: '/* Especificidade (ID, Classe, Elemento) */\np { }                    /* 0,0,1 */\n.destaque { }            /* 0,1,0 */\np.destaque { }           /* 0,1,1 */\n#cabecalho { }           /* 1,0,0 */\n#cabecalho .nav li { }   /* 1,1,1 */\n\n/* Qual ganha? */\np { color: blue; }              /* 0,0,1 */\n.texto { color: red; }          /* 0,1,0 - GANHA */\np.texto { color: green; }       /* 0,1,1 - GANHA */\n#id { color: purple; }          /* 1,0,0 - GANHA */\n\n/* Em caso de empate: última regra ganha */\n.classe { color: red; }\n.classe { color: blue; } /* blue ganha */\n\n/* ❌ Evite IDs para CSS */\n#menu .item.active { } /* difícil sobrescrever */\n/* ✅ Prefira classes */\n.menu .item.active { }',
                    },
                ],
                tips: [
                    'Prefira classes a IDs para estilização',
                    'Use combinadores para evitar classes extras',
                    ':hover/:focus são essenciais para UX',
                    '::before/::after precisam de content',
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Como seleciona-se uma classe em CSS?',
                    options: ['#nome', '.nome', 'nome', '@nome'],
                    correctAnswer: 1,
                    explanation: 'Classes são selecionadas com ponto (.) antes do nome',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Como seleciona-se um ID em CSS?',
                    options: ['.nome', '#nome', '*nome', '&nome'],
                    correctAnswer: 1,
                    explanation: 'IDs são selecionados com cerquilha (#) antes do nome',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'multiple-choice',
                    question: 'Qual seletor seleciona todos os elementos?',
                    options: ['all', '*', '#all', '.all'],
                    correctAnswer: 1,
                    explanation: 'O asterisco (*) é o seletor universal que seleciona tudo',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'fill-blank',
                    question: 'Complete: ____destaque { color: red; } (seletor de classe)',
                    correctAnswer: '.',
                    explanation: 'Classes usam ponto (.) como prefixo no seletor',
                    points: 15,
                },
                {
                    id: 'q5',
                    type: 'true-false',
                    question: 'IDs podem ser reutilizados em múltiplos elementos',
                    correctAnswer: 'false',
                    explanation: 'IDs devem ser únicos na página. Use classes para reutilização',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Como selecionar múltiplos elementos diferentes?',
                    options: ['h1 + h2', 'h1 h2', 'h1, h2', 'h1 > h2'],
                    correctAnswer: 2,
                    explanation: 'Vírgula (,) separa múltiplos seletores independentes',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'multiple-choice',
                    question: 'O que "div p" seleciona?',
                    options: ['div E p juntos', 'p dentro de div', 'div ou p', 'p após div'],
                    correctAnswer: 1,
                    explanation: 'Espaço seleciona descendentes (p dentro de div)',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'multiple-choice',
                    question: 'O que "div > p" seleciona?',
                    options: ['Qualquer p em div', 'Apenas p filho direto de div', 'div maior que p', 'p após div'],
                    correctAnswer: 1,
                    explanation: '> seleciona apenas filhos diretos, não descendentes',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'fill-blank',
                    question: 'Complete: p____.destaque { } (p com classe destaque)',
                    correctAnswer: '.',
                    explanation: 'Elemento.classe seleciona elementos específicos com classe',
                    points: 15,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'O que "h1 + p" seleciona?',
                    options: ['p dentro de h1', 'p filho de h1', 'p imediatamente após h1', 'Todos p após h1'],
                    correctAnswer: 2,
                    explanation: '+ é seletor de irmão adjacente (elemento imediatamente após)',
                    points: 15,
                },
            ],
        },

    ],
};

// ============================================
// MÓDULO 2: CORES E BACKGROUNDS
// ============================================

export const CSS_CORES: LearningModule = {
    id: 'css-cores',
    name: 'Cores e Backgrounds',
    description: 'Domine cores, gradientes e imagens de fundo',
    icon: '🖌️',
    difficulty: 'beginner',
    requiredXP: 200,
    lessons: [
        {
            id: 'cores-css',
            title: 'Cores em CSS',
            description: 'Aprenda as diferentes formas de definir cores',
            xpReward: 100,
            estimatedTime: 15,
            content: {
                introduction: 'CSS oferece várias formas de definir cores: nomes, hexadecimal (HEX), RGB, RGBA, HSL e HSLA.',
                sections: [
                    {
                        title: 'Cores por Nome',
                        text: 'CSS reconhece 140 nomes de cores em inglês como red, blue, green, yellow, etc.',
                        code: 'p {\n  color: red;\n  background-color: lightblue;\n}',
                    },
                    {
                        title: 'Cores Hexadecimais (HEX)',
                        text: 'Formato #RRGGBB onde cada par representa vermelho, verde e azul de 00 a FF.',
                        code: 'h1 {\n  color: #ff0000; /* vermelho */\n  background: #3498db; /* azul */\n}\n\n/* Forma curta */\np {\n  color: #f00; /* vermelho */\n}',
                    },
                    {
                        title: 'RGB e RGBA',
                        text: 'RGB usa valores de 0-255 para vermelho, verde e azul. RGBA adiciona transparência (alpha) de 0 a 1.',
                        code: '.box {\n  background: rgb(255, 0, 0);\n}\n\n.transparent {\n  background: rgba(0, 0, 0, 0.5); /* 50% transparente */\n}',
                    },
                    {
                        title: 'HSL e HSLA',
                        text: 'HSL define cores por Matiz (0-360), Saturação (0-100%) e Luminosidade (0-100%).',
                        code: '.hsl-example {\n  color: hsl(120, 100%, 50%); /* verde */\n  background: hsla(240, 100%, 50%, 0.3);\n}',
                    },
                ],
                tips: [
                    'Use HEX para cores simples',
                    'Use RGBA quando precisar de transparência',
                    'HSL é mais intuitivo para ajustes de cor',
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual é o formato correto de cor hexadecimal?',
                    options: ['#RRGGBB', 'rgb(r,g,b)', 'hsl(h,s,l)', 'color(red)'],
                    correctAnswer: 0,
                    explanation: 'Cores hexadecimais usam # seguido de 6 dígitos (RRGGBB)',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que o "A" representa em RGBA?',
                    options: ['Azul', 'Amarelo', 'Alpha (transparência)', 'Amplitude'],
                    correctAnswer: 2,
                    explanation: 'Alpha controla a transparência, de 0 (invisível) a 1 (opaco)',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: rgba(255, 0, 0, ____) para 50% transparente',
                    correctAnswer: '0.5',
                    explanation: 'O valor 0.5 representa 50% de opacidade/transparência',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: '#000000 representa a cor preta',
                    correctAnswer: 'true',
                    explanation: '#000000 é preto (todos zeros) e #FFFFFF é branco',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual cor é #FF0000?',
                    options: ['Azul', 'Verde', 'Vermelho', 'Preto'],
                    correctAnswer: 2,
                    explanation: 'FF no primeiro par (vermelho) com zeros nos outros = vermelho puro',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Qual cor é #00FF00?',
                    options: ['Azul', 'Verde', 'Vermelho', 'Amarelo'],
                    correctAnswer: 1,
                    explanation: 'FF no segundo par (green) = verde puro',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'fill-blank',
                    question: 'Complete: #____ é a cor branca',
                    correctAnswer: 'FFFFFF',
                    explanation: '#FFFFFF (todos FF) é branco puro',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'multiple-choice',
                    question: 'Em HSL, o que S representa?',
                    options: ['Size', 'Saturation', 'Shadow', 'Shade'],
                    correctAnswer: 1,
                    explanation: 'S = Saturation (saturação) de 0% a 100%',
                    points: 10,
                },
                {
                    id: 'q9',
                    type: 'true-false',
                    question: 'rgba(0,0,0,0) é completamente transparente',
                    correctAnswer: 'true',
                    explanation: 'Alpha 0 significa completamente transparente/invisível',
                    points: 10,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: '#F00 é igual a:',
                    options: ['#0000FF', '#FF0000', '#00FF00', '#FFFFFF'],
                    correctAnswer: 1,
                    explanation: '#F00 é forma curta de #FF0000 (vermelho)',
                    points: 15,
                },
            ],
        },

        {
            id: 'backgrounds-css',
            title: 'Backgrounds',
            description: 'Imagens de fundo, gradientes e propriedades de background',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'A propriedade background permite adicionar cores, imagens e gradientes ao fundo dos elementos.',
                sections: [
                    {
                        title: 'Background Color',
                        text: 'Define a cor de fundo de um elemento.',
                        code: 'div {\n  background-color: #f0f0f0;\n}',
                    },
                    {
                        title: 'Background Image',
                        text: 'Adiciona uma imagem como fundo do elemento.',
                        code: '.hero {\n  background-image: url("imagem.jpg");\n  background-size: cover;\n  background-position: center;\n}',
                    },
                    {
                        title: 'Gradientes',
                        text: 'Cria transições suaves entre cores com linear-gradient ou radial-gradient.',
                        code: '.gradient {\n  background: linear-gradient(to right, red, blue);\n}\n\n.radial {\n  background: radial-gradient(circle, white, black);\n}',
                    },
                    {
                        title: 'Background Shorthand',
                        text: 'Combine todas as propriedades de background em uma única declaração.',
                        code: '.box {\n  background: #333 url("bg.jpg") no-repeat center/cover;\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual propriedade define uma imagem de fundo?',
                    options: ['background-color', 'background-image', 'background-src', 'image-background'],
                    correctAnswer: 1,
                    explanation: 'background-image define a imagem de fundo com url()',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que background-size: cover faz?',
                    options: ['Esconde o fundo', 'Preenche todo o elemento', 'Remove a imagem', 'Centraliza a imagem'],
                    correctAnswer: 1,
                    explanation: 'cover redimensiona a imagem para cobrir todo o elemento',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: background: linear-____(to right, red, blue);',
                    correctAnswer: 'gradient',
                    explanation: 'linear-gradient cria um gradiente em linha reta',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'É possível ter múltiplas imagens de fundo',
                    correctAnswer: 'true',
                    explanation: 'CSS permite múltiplos backgrounds separados por vírgula',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual valor de background-repeat impede a repetição?',
                    options: ['repeat', 'no-repeat', 'stop', 'once'],
                    correctAnswer: 1,
                    explanation: 'no-repeat impede que a imagem de fundo se repita',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Qual a diferença entre cover e contain?',
                    options: ['São iguais', 'cover corta, contain mostra toda imagem', 'contain corta, cover mostra tudo', 'Nenhuma'],
                    correctAnswer: 1,
                    explanation: 'cover preenche (pode cortar), contain mostra toda a imagem',
                    points: 15,
                },
                {
                    id: 'q7',
                    type: 'fill-blank',
                    question: 'Complete: background-____: center center;',
                    correctAnswer: 'position',
                    explanation: 'background-position determina onde a imagem é posicionada',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'multiple-choice',
                    question: 'O que radial-gradient cria?',
                    options: ['Gradiente linear', 'Gradiente circular', 'Gradiente angular', 'Imagem sólida'],
                    correctAnswer: 1,
                    explanation: 'radial-gradient cria gradientes que irradiam do centro',
                    points: 10,
                },
                {
                    id: 'q9',
                    type: 'true-false',
                    question: 'background-attachment: fixed mantém imagem fixa no scroll',
                    correctAnswer: 'true',
                    explanation: 'fixed faz a imagem permanecer parada enquanto o conteúdo rola',
                    points: 10,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'Como definir gradiente de 45 graus?',
                    options: ['linear-gradient(45, red, blue)', 'linear-gradient(45deg, red, blue)', 'gradient(45deg)', 'linear(45deg)'],
                    correctAnswer: 1,
                    explanation: 'Use deg para especificar ângulo: linear-gradient(45deg, ...)',
                    points: 15,
                },
            ],
        },

    ],
};

// ============================================
// MÓDULO 3: TIPOGRAFIA
// ============================================

export const CSS_TIPOGRAFIA: LearningModule = {
    id: 'css-tipografia',
    name: 'Tipografia',
    description: 'Fontes, tamanhos, espaçamentos e estilização de texto',
    icon: '✒️',
    difficulty: 'beginner',
    requiredXP: 400,
    lessons: [
        {
            id: 'fontes-css',
            title: 'Fontes e Famílias',
            description: 'Escolha e aplique fontes em seus projetos',
            xpReward: 100,
            estimatedTime: 15,
            content: {
                introduction: 'A tipografia é essencial para a legibilidade e estética de um site. CSS oferece controle total sobre fontes.',
                sections: [
                    {
                        title: 'Font-Family',
                        text: 'Define a família de fontes. Sempre inclua fontes de fallback.',
                        code: 'body {\n  font-family: "Helvetica Neue", Arial, sans-serif;\n}',
                    },
                    {
                        title: 'Font-Size',
                        text: 'Define o tamanho da fonte em px, em, rem ou outras unidades.',
                        code: 'p {\n  font-size: 16px;\n}\n\nh1 {\n  font-size: 2rem;\n}',
                    },
                    {
                        title: 'Font-Weight',
                        text: 'Define a espessura da fonte: normal, bold, ou valores numéricos (100-900).',
                        code: '.bold {\n  font-weight: bold;\n}\n\n.light {\n  font-weight: 300;\n}',
                    },
                    {
                        title: 'Google Fonts',
                        text: 'Use fontes gratuitas do Google Fonts para mais variedade.',
                        code: '/* No HTML */\n<link href="https://fonts.googleapis.com/css2?family=Roboto" rel="stylesheet">\n\n/* No CSS */\nbody {\n  font-family: "Roboto", sans-serif;\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual propriedade define a família de fontes?',
                    options: ['font-name', 'font-family', 'font-type', 'text-font'],
                    correctAnswer: 1,
                    explanation: 'font-family define a família de fontes a ser usada',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que font-weight: bold faz?',
                    options: ['Deixa o texto itálico', 'Deixa o texto em negrito', 'Aumenta o tamanho', 'Sublinha o texto'],
                    correctAnswer: 1,
                    explanation: 'font-weight: bold deixa o texto em negrito (mais grosso)',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: font-____: 16px;',
                    correctAnswer: 'size',
                    explanation: 'font-size define o tamanho da fonte',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'Sans-serif é uma fonte específica, não um tipo',
                    correctAnswer: 'false',
                    explanation: 'Sans-serif é uma categoria genérica de fontes sem serifas',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual unidade é relativa ao tamanho da fonte raiz?',
                    options: ['px', 'em', 'rem', '%'],
                    correctAnswer: 2,
                    explanation: 'rem (root em) é relativo ao font-size do elemento raiz (html)',
                    points: 10,
                },
            ],
        },
        {
            id: 'texto-css',
            title: 'Estilização de Texto',
            description: 'Alinhamento, decoração e espaçamento de texto',
            xpReward: 100,
            estimatedTime: 15,
            content: {
                introduction: 'Além de fontes, CSS permite controlar alinhamento, espaçamento e decoração de texto.',
                sections: [
                    {
                        title: 'Text-Align',
                        text: 'Alinha o texto horizontalmente: left, center, right ou justify.',
                        code: '.centered {\n  text-align: center;\n}\n\n.justified {\n  text-align: justify;\n}',
                    },
                    {
                        title: 'Text-Decoration',
                        text: 'Adiciona ou remove decorações como sublinhado e riscado.',
                        code: 'a {\n  text-decoration: none; /* remove sublinhado */\n}\n\n.strike {\n  text-decoration: line-through;\n}',
                    },
                    {
                        title: 'Line-Height',
                        text: 'Define a altura da linha, afetando o espaçamento vertical.',
                        code: 'p {\n  line-height: 1.6; /* 1.6x o tamanho da fonte */\n}',
                    },
                    {
                        title: 'Letter e Word Spacing',
                        text: 'Controla o espaço entre letras e palavras.',
                        code: '.spaced {\n  letter-spacing: 2px;\n  word-spacing: 4px;\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual propriedade centraliza texto horizontalmente?',
                    options: ['text-center', 'align: center', 'text-align: center', 'horizontal-align'],
                    correctAnswer: 2,
                    explanation: 'text-align: center centraliza o texto horizontalmente',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Como remover o sublinhado de links?',
                    options: ['underline: none', 'text-decoration: none', 'text-line: none', 'decoration: off'],
                    correctAnswer: 1,
                    explanation: 'text-decoration: none remove qualquer decoração de texto',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: line-____: 1.5;',
                    correctAnswer: 'height',
                    explanation: 'line-height define a altura da linha do texto',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'text-transform: uppercase deixa todas as letras maiúsculas',
                    correctAnswer: 'true',
                    explanation: 'uppercase transforma todo o texto em letras maiúsculas',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'O que letter-spacing controla?',
                    options: ['Espaço entre linhas', 'Espaço entre letras', 'Espaço entre parágrafos', 'Tamanho das letras'],
                    correctAnswer: 1,
                    explanation: 'letter-spacing define o espaço entre cada letra',
                    points: 10,
                },
            ],
        },
    ],
};

// Continua no próximo módulo...

// ============================================
// MÓDULO 4: BOX MODEL
// ============================================

export const CSS_BOX_MODEL: LearningModule = {
    id: 'css-box-model',
    name: 'Box Model e Espaçamento',
    description: 'Margin, padding, border e dimensões',
    icon: '📦',
    difficulty: 'intermediate',
    requiredXP: 600,
    lessons: [
        {
            id: 'box-model',
            title: 'O Box Model',
            description: 'Entenda como o CSS calcula o tamanho dos elementos',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Todo elemento HTML é uma "caixa" composta por: conteúdo, padding, border e margin. Entender o Box Model é essencial.',
                sections: [
                    {
                        title: 'Componentes do Box Model',
                        text: 'Content: o conteúdo do elemento. Padding: espaço interno. Border: borda ao redor. Margin: espaço externo.',
                        code: '.box {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid black;\n  margin: 10px;\n}',
                    },
                    {
                        title: 'Width e Height',
                        text: 'Define a largura e altura do conteúdo. Por padrão, padding e border são adicionados.',
                        code: 'div {\n  width: 100%;\n  max-width: 800px;\n  height: auto;\n  min-height: 200px;\n}',
                    },
                    {
                        title: 'Box-Sizing',
                        text: 'box-sizing: border-box inclui padding e border no cálculo de width/height.',
                        code: '* {\n  box-sizing: border-box;\n}\n\n.card {\n  width: 300px; /* inclui padding e border */\n  padding: 20px;\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Quais são os 4 componentes do Box Model?',
                    options: ['Top, Right, Bottom, Left', 'Content, Padding, Border, Margin', 'Width, Height, Depth, Margin', 'Header, Body, Footer, Aside'],
                    correctAnswer: 1,
                    explanation: 'O Box Model é: Content (conteúdo), Padding, Border e Margin',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que box-sizing: border-box faz?',
                    options: ['Remove bordas', 'Inclui padding/border no width', 'Adiciona sombra', 'Centraliza o elemento'],
                    correctAnswer: 1,
                    explanation: 'border-box faz width/height incluir padding e border no cálculo',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'true-false',
                    question: 'Margin é o espaço interno do elemento',
                    correctAnswer: 'false',
                    explanation: 'Margin é externo. Padding é o espaço interno.',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'fill-blank',
                    question: 'Complete: ____-sizing: border-box;',
                    correctAnswer: 'box',
                    explanation: 'box-sizing controla como width/height são calculados',
                    points: 15,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual propriedade define a largura máxima?',
                    options: ['width-max', 'max-width', 'limit-width', 'top-width'],
                    correctAnswer: 1,
                    explanation: 'max-width define a largura máxima que um elemento pode ter',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Qual é o box-sizing padrão do CSS?',
                    options: ['border-box', 'content-box', 'padding-box', 'margin-box'],
                    correctAnswer: 1,
                    explanation: 'content-box é o padrão - width/height só incluem conteúdo',
                    points: 15,
                },
                {
                    id: 'q7',
                    type: 'true-false',
                    question: 'Padding nunca pode ter valores negativos',
                    correctAnswer: 'true',
                    explanation: 'Padding só aceita valores positivos. Margin pode ser negativo.',
                    points: 10,
                },
                {
                    id: 'q8',
                    type: 'fill-blank',
                    question: 'Complete: ____-height: 100px; (altura mínima)',
                    correctAnswer: 'min',
                    explanation: 'min-height define a altura mínima do elemento',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'multiple-choice',
                    question: 'O que acontece com margins verticais adjacentes?',
                    options: ['Somam', 'Colapsam (o maior vence)', 'Anulam', 'Erro CSS'],
                    correctAnswer: 1,
                    explanation: 'Margin collapse: margins verticais adjacentes colapsam',
                    points: 15,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'width: 50% é relativo a quê?',
                    options: ['Viewport', 'Elemento pai', 'Body', 'Tela'],
                    correctAnswer: 1,
                    explanation: 'Porcentagens são relativas ao elemento pai direto',
                    points: 10,
                },
            ],
        },

        {
            id: 'margin-padding',
            title: 'Margin e Padding',
            description: 'Controle espaçamentos internos e externos',
            xpReward: 100,
            estimatedTime: 15,
            content: {
                introduction: 'Margin controla espaço externo, Padding controla espaço interno. Ambos aceitam 1 a 4 valores.',
                sections: [
                    {
                        title: 'Padding',
                        text: 'Espaço entre o conteúdo e a borda. Pode ser definido para cada lado.',
                        code: '.box {\n  padding: 20px; /* todos os lados */\n  padding: 10px 20px; /* vertical | horizontal */\n  padding: 10px 20px 30px 40px; /* top right bottom left */\n}',
                    },
                    {
                        title: 'Margin',
                        text: 'Espaço externo ao elemento. Mesma sintaxe do padding.',
                        code: '.card {\n  margin: 20px auto; /* centraliza horizontalmente */\n  margin-bottom: 30px;\n}',
                    },
                    {
                        title: 'Margin Auto',
                        text: 'margin: auto centraliza elementos de bloco horizontalmente.',
                        code: '.container {\n  width: 800px;\n  margin: 0 auto; /* centralizado */\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'O que padding: 10px 20px significa?',
                    options: ['10px em todos os lados', '10px vertical, 20px horizontal', '10px top, 20px bottom', '10px left, 20px right'],
                    correctAnswer: 1,
                    explanation: 'Com 2 valores: primeiro é vertical (top/bottom), segundo é horizontal (left/right)',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Como centralizar um elemento horizontalmente?',
                    options: ['margin: center', 'margin: 0 auto', 'align: center', 'position: center'],
                    correctAnswer: 1,
                    explanation: 'margin: 0 auto centraliza elementos de bloco com largura definida',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: margin-____: 20px; (para o lado inferior)',
                    correctAnswer: 'bottom',
                    explanation: 'margin-bottom define a margem inferior',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'Padding pode ter valores negativos',
                    correctAnswer: 'false',
                    explanation: 'Padding não aceita valores negativos. Margin sim.',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'margin: 10px 20px 30px 40px. Qual é o valor do right?',
                    options: ['10px', '20px', '30px', '40px'],
                    correctAnswer: 1,
                    explanation: 'A ordem é: top right bottom left (sentido horário)',
                    points: 10,
                },
            ],
        },
        {
            id: 'borders-css',
            title: 'Borders',
            description: 'Bordas, arredondamentos e estilos',
            xpReward: 100,
            estimatedTime: 15,
            content: {
                introduction: 'A propriedade border adiciona bordas aos elementos. Você pode controlar estilo, largura e cor.',
                sections: [
                    {
                        title: 'Border Básico',
                        text: 'A shorthand border aceita: largura, estilo e cor.',
                        code: '.box {\n  border: 2px solid black;\n}\n\n.dashed {\n  border: 1px dashed gray;\n}',
                    },
                    {
                        title: 'Border-Radius',
                        text: 'Arredonda os cantos do elemento.',
                        code: '.rounded {\n  border-radius: 8px;\n}\n\n.circle {\n  border-radius: 50%;\n}',
                    },
                    {
                        title: 'Bordas Individuais',
                        text: 'Defina bordas para cada lado separadamente.',
                        code: '.custom {\n  border-top: 3px solid blue;\n  border-bottom: 1px dotted gray;\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual é a ordem da shorthand border?',
                    options: ['cor estilo largura', 'largura estilo cor', 'estilo cor largura', 'cor largura estilo'],
                    correctAnswer: 1,
                    explanation: 'A ordem é: largura estilo cor (ex: 2px solid black)',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Como criar um círculo perfeito com CSS?',
                    options: ['border-radius: 100px', 'border-radius: 50%', 'shape: circle', 'round: true'],
                    correctAnswer: 1,
                    explanation: 'border-radius: 50% em um quadrado cria um círculo',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: border-____: 10px;',
                    correctAnswer: 'radius',
                    explanation: 'border-radius arredonda os cantos',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'border: none remove todas as bordas',
                    correctAnswer: 'true',
                    explanation: 'border: none ou border: 0 remove todas as bordas',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual NÃO é um estilo de borda válido?',
                    options: ['solid', 'dashed', 'dotted', 'striped'],
                    correctAnswer: 3,
                    explanation: 'striped não existe. Válidos: solid, dashed, dotted, double, etc.',
                    points: 10,
                },
            ],
        },
    ],
};

// ============================================
// MÓDULO 5: FLEXBOX E LAYOUT
// ============================================

export const CSS_FLEXBOX: LearningModule = {
    id: 'css-flexbox',
    name: 'Flexbox e Layout',
    description: 'Crie layouts flexíveis e responsivos',
    icon: '📐',
    difficulty: 'intermediate',
    requiredXP: 800,
    lessons: [
        {
            id: 'display-css',
            title: 'Display e Position',
            description: 'Controle como elementos são exibidos',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Display controla o tipo de caixa de renderização. Position controla o posicionamento.',
                sections: [
                    {
                        title: 'Display',
                        text: 'block, inline, inline-block, flex, grid, none.',
                        code: '.block { display: block; }\n.inline { display: inline; }\n.flex { display: flex; }\n.hidden { display: none; }',
                    },
                    {
                        title: 'Position',
                        text: 'static (padrão), relative, absolute, fixed, sticky.',
                        code: '.absolute {\n  position: absolute;\n  top: 0;\n  right: 0;\n}\n\n.fixed {\n  position: fixed;\n  bottom: 20px;\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual display oculta completamente o elemento?',
                    options: ['hidden', 'none', 'invisible', 'off'],
                    correctAnswer: 1,
                    explanation: 'display: none remove o elemento do fluxo da página',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Qual position é relativo à janela do navegador?',
                    options: ['relative', 'absolute', 'fixed', 'static'],
                    correctAnswer: 2,
                    explanation: 'fixed posiciona relativo à viewport (janela)',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: display: ____;',
                    correctAnswer: 'flex',
                    explanation: 'display: flex ativa o Flexbox no elemento',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'position: static é o valor padrão',
                    correctAnswer: 'true',
                    explanation: 'Elementos têm position: static por padrão',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual display permite definir width/height em elementos inline?',
                    options: ['inline', 'block', 'inline-block', 'flex'],
                    correctAnswer: 2,
                    explanation: 'inline-block combina características de inline e block',
                    points: 10,
                },
            ],
        },
        {
            id: 'flexbox-basico',
            title: 'Flexbox Básico',
            description: 'Crie layouts flexíveis facilmente',
            xpReward: 150,
            estimatedTime: 25,
            content: {
                introduction: 'Flexbox é um sistema de layout unidimensional que facilita a distribuição de espaço entre itens.',
                sections: [
                    {
                        title: 'Container Flex',
                        text: 'Aplique display: flex ao container para ativar o Flexbox.',
                        code: '.container {\n  display: flex;\n  gap: 20px;\n}',
                    },
                    {
                        title: 'Justify-Content',
                        text: 'Alinha itens no eixo principal (horizontal por padrão).',
                        code: '.container {\n  display: flex;\n  justify-content: center; /* center, space-between, space-around */\n}',
                    },
                    {
                        title: 'Align-Items',
                        text: 'Alinha itens no eixo cruzado (vertical por padrão).',
                        code: '.container {\n  display: flex;\n  align-items: center; /* center, flex-start, flex-end, stretch */\n}',
                    },
                    {
                        title: 'Flex-Direction',
                        text: 'Define a direção dos itens: row, row-reverse, column, column-reverse.',
                        code: '.vertical {\n  flex-direction: column;\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual propriedade ativa o Flexbox?',
                    options: ['flex: on', 'display: flex', 'flexbox: true', 'layout: flex'],
                    correctAnswer: 1,
                    explanation: 'display: flex no container ativa o Flexbox',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que justify-content: space-between faz?',
                    options: ['Centraliza itens', 'Espaço igual entre itens', 'Agrupa à esquerda', 'Empilha verticalmente'],
                    correctAnswer: 1,
                    explanation: 'space-between distribui espaço igual ENTRE os itens',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'multiple-choice',
                    question: 'Qual propriedade centraliza verticalmente em Flexbox?',
                    options: ['justify-content', 'align-items', 'text-align', 'vertical-align'],
                    correctAnswer: 1,
                    explanation: 'align-items alinha no eixo cruzado (vertical por padrão)',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'fill-blank',
                    question: 'Complete: flex-____: column;',
                    correctAnswer: 'direction',
                    explanation: 'flex-direction define a direção do eixo principal',
                    points: 15,
                },
                {
                    id: 'q5',
                    type: 'true-false',
                    question: 'gap funciona em Flexbox para espaçar itens',
                    correctAnswer: 'true',
                    explanation: 'gap define espaço entre itens flex/grid',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Como centralizar um item horizontal E verticalmente?',
                    options: ['margin: auto', 'justify-content: center + align-items: center', 'text-align: center', 'center: true'],
                    correctAnswer: 1,
                    explanation: 'Combine justify-content e align-items com center',
                    points: 10,
                },
            ],
        },
    ],
};

// ============================================
// MÓDULO 6: EFEITOS E ANIMAÇÕES
// ============================================

export const CSS_EFEITOS: LearningModule = {
    id: 'css-efeitos',
    name: 'Efeitos e Animações',
    description: 'Transitions, transforms e animações CSS',
    icon: '✨',
    difficulty: 'advanced',
    requiredXP: 1000,
    lessons: [
        {
            id: 'transitions',
            title: 'Transitions',
            description: 'Crie transições suaves entre estados',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Transitions animam mudanças de propriedades CSS de forma suave.',
                sections: [
                    {
                        title: 'Transition Básico',
                        text: 'Defina quais propriedades animar e a duração.',
                        code: '.button {\n  background: blue;\n  transition: background 0.3s ease;\n}\n\n.button:hover {\n  background: darkblue;\n}',
                    },
                    {
                        title: 'Múltiplas Propriedades',
                        text: 'Anime várias propriedades ou use all.',
                        code: '.card {\n  transition: all 0.3s ease;\n}\n\n.card:hover {\n  transform: scale(1.05);\n  box-shadow: 0 10px 20px rgba(0,0,0,0.2);\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual propriedade cria transições suaves?',
                    options: ['animation', 'transition', 'smooth', 'ease'],
                    correctAnswer: 1,
                    explanation: 'transition define transições entre estados',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'fill-blank',
                    question: 'Complete: transition: background ____s ease;',
                    correctAnswer: '0.3',
                    explanation: 'O segundo valor é a duração em segundos',
                    points: 15,
                },
                {
                    id: 'q3',
                    type: 'multiple-choice',
                    question: 'O que transition: all faz?',
                    options: ['Anima todas as propriedades', 'Desativa animações', 'Anima todos os elementos', 'Reseta estilos'],
                    correctAnswer: 0,
                    explanation: 'all anima qualquer propriedade que mudar',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'Transitions precisam de um trigger como :hover',
                    correctAnswer: 'true',
                    explanation: 'Transitions animam mudanças de estado (hover, focus, etc.)',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual timing function começa devagar e acelera?',
                    options: ['ease-out', 'ease-in', 'linear', 'ease'],
                    correctAnswer: 1,
                    explanation: 'ease-in começa devagar e acelera no final',
                    points: 10,
                },
            ],
        },
        {
            id: 'transforms',
            title: 'Transforms',
            description: 'Rotacione, escale e mova elementos',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Transform permite modificar elementos visualmente sem afetar o layout.',
                sections: [
                    {
                        title: 'Scale',
                        text: 'Aumenta ou diminui o tamanho do elemento.',
                        code: '.zoom {\n  transform: scale(1.2); /* 120% do tamanho */\n}',
                    },
                    {
                        title: 'Rotate',
                        text: 'Rotaciona o elemento em graus.',
                        code: '.spin {\n  transform: rotate(45deg);\n}',
                    },
                    {
                        title: 'Translate',
                        text: 'Move o elemento sem afetar outros.',
                        code: '.move {\n  transform: translateX(50px);\n  transform: translate(20px, 30px);\n}',
                    },
                    {
                        title: 'Combinando Transforms',
                        text: 'Aplique múltiplas transformações.',
                        code: '.complex {\n  transform: scale(1.1) rotate(5deg) translateY(-10px);\n}',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual transform dobra o tamanho do elemento?',
                    options: ['scale(2)', 'size(200%)', 'zoom(2x)', 'grow(double)'],
                    correctAnswer: 0,
                    explanation: 'scale(2) aumenta para 200% (o dobro)',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Qual unidade é usada em rotate?',
                    options: ['px', 'deg', 'rem', '%'],
                    correctAnswer: 1,
                    explanation: 'rotate usa deg (graus) como unidade',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: transform: ____X(100px);',
                    correctAnswer: 'translate',
                    explanation: 'translateX move horizontalmente',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'Transform afeta o espaço ocupado pelo elemento no layout',
                    correctAnswer: 'false',
                    explanation: 'Transform é visual apenas, não afeta o layout',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'O que rotate(180deg) faz?',
                    options: ['Vira de cabeça para baixo', 'Gira 180 pixels', 'Move 180 graus para direita', 'Aumenta 180%'],
                    correctAnswer: 0,
                    explanation: '180 graus = meio giro = de cabeça para baixo',
                    points: 10,
                },
            ],
        },
    ],
};

// ============================================
// EXPORTAÇÃO DOS MÓDULOS CSS
// ============================================

export const CSS_MODULES: LearningModule[] = [
    CSS_FUNDAMENTOS,
    CSS_CORES,
    CSS_TIPOGRAFIA,
    CSS_BOX_MODEL,
    CSS_FLEXBOX,
    CSS_EFEITOS,
];
