// CodeQuest - JavaScript Learning Content
// Curso completo em Português com módulos bem categorizados

import { LearningModule } from './lessons';

// ============================================
// MÓDULO 1: FUNDAMENTOS JAVASCRIPT
// ============================================

export const JS_FUNDAMENTOS: LearningModule = {
    id: 'js-fundamentos',
    name: 'Fundamentos JavaScript',
    description: 'Aprenda a base do JavaScript: sintaxe, variáveis e operadores',
    icon: '⚡',
    difficulty: 'beginner',
    lessons: [
        {
            id: 'intro-js',
            title: 'Introdução ao JavaScript',
            description: 'O que é JavaScript, o que ele pode fazer e como usá-lo',
            xpReward: 150,
            estimatedTime: 25,
            content: {
                introduction: 'JavaScript é a linguagem de programação mais popular da web. Ela permite criar páginas interativas e dinâmicas, manipular elementos HTML, alterar estilos CSS e responder a ações do usuário em tempo real. Criada por Brendan Eich em 1995, hoje JavaScript pode rodar tanto no navegador quanto em servidores usando Node.js.',
                sections: [
                    {
                        title: 'O que é JavaScript?',
                        text: 'JavaScript (JS) é uma linguagem de programação de alto nível, interpretada e dinâmica. É a linguagem padrão para desenvolvimento web, rodando em todos os navegadores modernos. JavaScript pode calcular, manipular e validar dados, além de atualizar e modificar tanto HTML quanto CSS dinamicamente. Junto com HTML (estrutura) e CSS (estilo), JavaScript forma a tríade fundamental do desenvolvimento front-end.',
                        code: '// JavaScript pode fazer muitas coisas:\n// 1. Manipular HTML\ndocument.getElementById("titulo").innerHTML = "Novo Título";\n\n// 2. Alterar CSS\ndocument.getElementById("texto").style.color = "blue";\n\n// 3. Responder a eventos\ndocument.getElementById("botao").onclick = function() {\n  alert("Clicou!");\n};',
                    },
                    {
                        title: 'JavaScript Pode Mudar Conteúdo HTML',
                        text: 'Um dos métodos JavaScript HTML mais usados é getElementById(). Este método encontra um elemento pelo seu id e permite modificar seu conteúdo usando innerHTML. JavaScript aceita tanto aspas duplas quanto simples para strings, tornando-o flexível para diferentes situações.',
                        code: '// Mudando o conteúdo de um elemento\ndocument.getElementById("demo").innerHTML = "Olá JavaScript!";\n\n// Usando aspas simples (também funciona)\ndocument.getElementById(\'demo\').innerHTML = \'Olá JavaScript!\';\n\n// Adicionando HTML dinamicamente\ndocument.getElementById("lista").innerHTML = "<li>Item 1</li><li>Item 2</li>";',
                    },
                    {
                        title: 'JavaScript Pode Mudar Estilos CSS',
                        text: 'Alterar o estilo de um elemento HTML é uma variação de alterar um atributo HTML. Com JavaScript você pode modificar qualquer propriedade CSS de um elemento, criando efeitos visuais dinâmicos sem precisar recarregar a página.',
                        code: '// Mudando a cor do texto\ndocument.getElementById("titulo").style.color = "red";\n\n// Mudando o tamanho da fonte\ndocument.getElementById("texto").style.fontSize = "24px";\n\n// Múltiplas propriedades\nconst elemento = document.getElementById("caixa");\nelemento.style.backgroundColor = "#3498db";\nelemento.style.padding = "20px";\nelemento.style.borderRadius = "10px";',
                    },
                    {
                        title: 'JavaScript Pode Mostrar e Esconder Elementos',
                        text: 'JavaScript pode controlar a visibilidade de elementos usando a propriedade display do CSS. Isso é muito útil para criar menus dropdown, modais, abas e conteúdo que aparece/desaparece baseado em ações do usuário.',
                        code: '// Escondendo um elemento\ndocument.getElementById("popup").style.display = "none";\n\n// Mostrando um elemento\ndocument.getElementById("popup").style.display = "block";\n\n// Função para alternar visibilidade\nfunction toggleMenu() {\n  const menu = document.getElementById("menu");\n  if (menu.style.display === "none") {\n    menu.style.display = "block";\n  } else {\n    menu.style.display = "none";\n  }\n}',
                    },
                    {
                        title: 'JavaScript no HTML',
                        text: 'JavaScript pode ser adicionado ao HTML de duas formas: inline com a tag <script> ou em arquivo externo. A tag <script> pode conter código JavaScript diretamente ou referenciar um arquivo .js externo. Para projetos maiores, sempre prefira arquivos externos pois permitem cache, reutilização e melhor organização.',
                        code: '<!-- Script interno (inline) -->\n<script>\n  console.log("Olá do script interno!");\n  alert("Bem-vindo!");\n</script>\n\n<!-- Script externo (recomendado) -->\n<script src="js/app.js"></script>\n\n<!-- Múltiplos arquivos -->\n<script src="js/utils.js"></script>\n<script src="js/main.js"></script>',
                    },
                    {
                        title: 'Onde Colocar o Script',
                        text: 'Scripts podem ser colocados no <head> ou no <body>. Colocar scripts no final do <body> é a prática mais comum pois permite que o HTML carregue primeiro. Alternativamente, use o atributo defer para carregar scripts no head sem bloquear o carregamento da página. O atributo async carrega o script em paralelo e executa assim que estiver pronto.',
                        code: '<!-- NO HEAD com defer (recomendado para scripts externos) -->\n<head>\n  <script src="app.js" defer></script>\n</head>\n\n<!-- NO FINAL DO BODY (método tradicional) -->\n<body>\n  <h1>Meu Site</h1>\n  <p>Conteúdo...</p>\n  \n  <!-- Scripts aqui, após todo o HTML -->\n  <script src="app.js"></script>\n</body>\n\n<!-- async vs defer:\n     async: executa assim que carrega (ordem não garantida)\n     defer: executa após HTML carregar (mantém ordem) -->',
                    },
                    {
                        title: 'Console do Navegador',
                        text: 'O console é uma ferramenta essencial para desenvolvimento JavaScript. Use console.log() para debug e exibir valores, console.warn() para avisos (amarelo), console.error() para erros (vermelho), e console.table() para exibir dados em formato de tabela. Acesse o console pressionando F12 no navegador.',
                        code: '// Mensagem básica\nconsole.log("Olá, desenvolvedor!");\n\n// Exibindo variáveis\nconst nome = "Maria";\nconst idade = 25;\nconsole.log("Nome:", nome, "Idade:", idade);\n\n// Tipos de mensagem\nconsole.warn("⚠️ Atenção: valor pode ser nulo");\nconsole.error("❌ Erro: arquivo não encontrado");\nconsole.info("ℹ️ Versão 1.0.0");\n\n// Exibindo objetos/arrays como tabela\nconst usuarios = [{nome: "Ana", idade: 20}, {nome: "João", idade: 25}];\nconsole.table(usuarios);',
                    },
                    {
                        title: 'JavaScript vs Java',
                        text: 'Apesar do nome similar, JavaScript e Java são linguagens completamente diferentes em conceito e design. JavaScript foi criado por Brendan Eich em 1995 na Netscape. Em 1997, tornou-se padrão ECMA com o nome oficial ECMAScript. JavaScript é interpretado, dinâmico e tipado dinamicamente; Java é compilado, orientado a objetos e tipado estaticamente.',
                        code: '// JavaScript: linguagem dinâmica\nlet x = 10;        // número\nx = "texto";       // agora é string (tipagem dinâmica)\nx = [1, 2, 3];     // agora é array\n\n// JavaScript moderno (ES6+)\nconst somar = (a, b) => a + b;  // arrow function\nconst { nome, idade } = pessoa; // destructuring\nconst template = `Nome: ${nome}`; // template literals',
                    },
                ],
                tips: [
                    'Sempre use o console (F12) para debug e entender erros',
                    'Prefira scripts externos e use defer no head',
                    'Mantenha JavaScript separado do HTML para melhor organização',
                    'Teste seu código em diferentes navegadores',
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual tag é usada para adicionar JavaScript ao HTML?',
                    options: ['<javascript>', '<js>', '<script>', '<code>'],
                    correctAnswer: 2,
                    explanation: 'A tag <script> é usada para incluir JavaScript no HTML',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Qual comando exibe mensagens no console?',
                    options: ['print()', 'echo()', 'console.log()', 'display()'],
                    correctAnswer: 2,
                    explanation: 'console.log() é o método padrão para exibir no console',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'true-false',
                    question: 'JavaScript só funciona em navegadores',
                    correctAnswer: 'false',
                    explanation: 'JavaScript também roda em servidores com Node.js',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'fill-blank',
                    question: 'Complete: <script src="app.____"></script>',
                    correctAnswer: 'js',
                    explanation: 'Arquivos JavaScript usam a extensão .js',
                    points: 15,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Onde é recomendado colocar o <script>?',
                    options: ['No início do head', 'No final do body', 'Antes do DOCTYPE', 'No meio do body'],
                    correctAnswer: 1,
                    explanation: 'Final do body permite que o HTML carregue primeiro',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'O que o atributo defer faz no script?',
                    options: ['Atrasa o carregamento', 'Executa após o HTML carregar', 'Remove o script', 'Executa imediatamente'],
                    correctAnswer: 1,
                    explanation: 'defer faz o script executar depois que o HTML é parseado',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'true-false',
                    question: 'console.error() exibe mensagens de erro no console',
                    correctAnswer: 'true',
                    explanation: 'console.error() é usado para exibir erros com formatação vermelha',
                    points: 10,
                },
                {
                    id: 'q8',
                    type: 'multiple-choice',
                    question: 'Em que ano JavaScript foi criado?',
                    options: ['1990', '1995', '2000', '2005'],
                    correctAnswer: 1,
                    explanation: 'JavaScript foi criado por Brendan Eich em 1995 na Netscape',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'fill-blank',
                    question: 'Complete: console.____("Aviso importante")',
                    correctAnswer: 'warn',
                    explanation: 'console.warn() exibe avisos com destaque amarelo no console',
                    points: 15,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'Qual é a diferença entre async e defer?',
                    options: ['São iguais', 'async bloqueia, defer não', 'async executa assim que carrega, defer espera o HTML', 'defer é mais rápido'],
                    correctAnswer: 2,
                    explanation: 'async executa imediatamente após carregar; defer espera o HTML terminar',
                    points: 15,
                },
            ],
        },

        {
            id: 'variaveis-js',
            title: 'Variáveis em JavaScript',
            description: 'let, const e var - declaração, escopo e boas práticas',
            xpReward: 150,
            estimatedTime: 25,
            content: {
                introduction: 'Variáveis são containers para armazenar valores de dados. Em JavaScript moderno, usamos let e const para declarar variáveis. Entender quando usar cada uma e como funciona o escopo é fundamental para escrever código limpo e evitar bugs difíceis de encontrar.',
                sections: [
                    {
                        title: 'Declarando Variáveis com let',
                        text: 'let é a forma moderna de declarar variáveis que podem ter seu valor alterado. Use let quando você precisa de uma variável cujo valor vai mudar durante a execução do programa, como contadores, acumuladores ou estados.',
                        code: '// Declaração básica\nlet nome = "Maria";\nlet idade = 25;\nlet ativo = true;\n\n// Reatribuição (mudar o valor)\nnome = "João";      // OK!\nidade = idade + 1;  // OK!\nativo = false;      // OK!\n\n// Declarar sem valor inicial (undefined)\nlet resultado;\nconsole.log(resultado); // undefined\nresultado = 42;',
                    },
                    {
                        title: 'Declarando Constantes com const',
                        text: 'const é usada para declarar valores que NÃO devem ser reatribuídos. Use const como padrão e só mude para let quando realmente precisar alterar o valor. Isso torna o código mais previsível e evita bugs acidentais.',
                        code: '// Constantes (valores fixos)\nconst PI = 3.14159;\nconst URL_API = "https://api.exemplo.com";\nconst MAX_TENTATIVAS = 3;\n\n// Erro! Não pode reatribuir const\n// PI = 3.14; // TypeError!\n\n// ATENÇÃO: const com objetos e arrays\nconst usuario = { nome: "Ana", idade: 20 };\nusuario.idade = 21;  // OK! Modifica propriedade\n// usuario = {};     // Erro! Não pode reatribuir\n\nconst numeros = [1, 2, 3];\nnumeros.push(4);     // OK! [1, 2, 3, 4]\n// numeros = [];     // Erro! Não pode reatribuir',
                    },
                    {
                        title: 'Por que Evitar var',
                        text: 'var é a forma antiga de declarar variáveis e tem comportamentos problemáticos: não respeita escopo de bloco, permite redeclaração e sofre hoisting de forma confusa. Em código moderno, sempre prefira let e const.',
                        code: '// Problema 1: var não respeita escopo de bloco\nif (true) {\n  var x = 10;  // "vaza" para fora do if\n  let y = 20;  // fica apenas dentro do if\n}\nconsole.log(x); // 10 (problemático!)\n// console.log(y); // Erro: y is not defined (correto!)\n\n// Problema 2: var permite redeclaração\nvar nome = "Ana";\nvar nome = "João"; // OK com var (bug fácil!)\n\nlet sobrenome = "Silva";\n// let sobrenome = "Santos"; // Erro! (proteção contra bugs)',
                    },
                    {
                        title: 'Escopo de Variáveis',
                        text: 'Escopo define onde uma variável pode ser acessada. let e const têm escopo de bloco (dentro de {}), enquanto var tem escopo de função. Variáveis declaradas fora de funções são globais e podem ser acessadas em qualquer lugar.',
                        code: '// Escopo Global\nconst GLOBAL = "acessível em todo lugar";\n\nfunction exemplo() {\n  // Escopo de Função\n  const local = "só dentro da função";\n  \n  if (true) {\n    // Escopo de Bloco\n    let bloco = "só dentro do if";\n    console.log(GLOBAL); // OK\n    console.log(local);  // OK\n    console.log(bloco);  // OK\n  }\n  \n  console.log(GLOBAL); // OK\n  console.log(local);  // OK\n  // console.log(bloco); // Erro! Fora do escopo\n}\n\nconsole.log(GLOBAL); // OK\n// console.log(local); // Erro! Fora da função',
                    },
                    {
                        title: 'Hoisting (Elevação)',
                        text: 'Hoisting é um comportamento do JavaScript onde declarações são "elevadas" para o topo do escopo. Com var, a declaração é elevada mas não o valor. Com let e const, existe uma "zona morta temporal" onde a variável existe mas não pode ser acessada.',
                        code: '// Hoisting com var (confuso!)\nconsole.log(x); // undefined (não erro!)\nvar x = 5;\n\n// Hoisting com let (mais seguro)\n// console.log(y); // Erro: Cannot access before initialization\nlet y = 5;\n\n// Hoisting de funções\nsaudacao(); // Funciona! "Olá"\nfunction saudacao() {\n  console.log("Olá");\n}\n\n// Arrow functions não sofrem hoisting\n// despedida(); // Erro!\nconst despedida = () => console.log("Tchau");',
                    },
                    {
                        title: 'Tipos de Dados',
                        text: 'JavaScript é dinamicamente tipado: uma variável pode armazenar qualquer tipo de valor. Os tipos primitivos são: string, number, boolean, undefined, null, symbol e bigint. Tipos complexos incluem objects e arrays.',
                        code: '// Tipos Primitivos\nlet texto = "Olá";           // string\nlet numero = 42;             // number\nlet decimal = 3.14;          // number\nlet verdade = true;          // boolean\nlet vazio = null;            // null (ausência intencional)\nlet indefinido;              // undefined (não atribuído)\n\n// Tipos Complexos\nlet pessoa = {               // object\n  nome: "Ana",\n  idade: 25\n};\nlet cores = ["vermelho", "azul"]; // array (é um object)\n\n// Verificando tipo\nconsole.log(typeof texto);   // "string"\nconsole.log(typeof numero);  // "number"\nconsole.log(typeof pessoa);  // "object"\nconsole.log(typeof cores);   // "object" (arrays são objetos!)',
                    },
                    {
                        title: 'Regras de Nomenclatura',
                        text: 'Nomes de variáveis devem começar com letra, $ ou _. Use camelCase para variáveis e funções, UPPER_SNAKE_CASE para constantes globais, e PascalCase para classes. Escolha nomes descritivos que expliquem o propósito da variável.',
                        code: '// camelCase para variáveis e funções\nlet nomeCompleto = "Maria Silva";\nlet idadeUsuario = 25;\nfunction calcularTotal() { }\n\n// UPPER_SNAKE_CASE para constantes globais\nconst MAX_TENTATIVAS = 3;\nconst API_URL = "https://api.com";\nconst SEGUNDOS_POR_HORA = 3600;\n\n// PascalCase para classes/construtores\nclass Usuario { }\nclass CarrinhoDeCompras { }\n\n// Nomes válidos\nlet _privado = "interno";\nlet $jquery = null;\nlet nome2 = "ok";\n\n// Nomes INVÁLIDOS\n// let 2nome = "erro";    // não pode começar com número\n// let meu-nome = "erro"; // hífen não permitido\n// let let = "erro";      // palavra reservada',
                    },
                ],
                tips: [
                    'Use const por padrão, só mude para let quando precisar',
                    'Nunca use var em código moderno',
                    'Declare variáveis o mais próximo possível de onde serão usadas',
                    'Escolha nomes descritivos: precoProduto é melhor que p',
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual palavra-chave é usada para constantes?',
                    options: ['let', 'var', 'const', 'constant'],
                    correctAnswer: 2,
                    explanation: 'const é usada para declarar constantes',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Qual convenção de nomenclatura é padrão em JavaScript?',
                    options: ['snake_case', 'camelCase', 'PascalCase', 'kebab-case'],
                    correctAnswer: 1,
                    explanation: 'camelCase é a convenção padrão para variáveis em JS',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'true-false',
                    question: 'const permite reatribuição de valor',
                    correctAnswer: 'false',
                    explanation: 'const não permite reatribuição após a declaração',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'fill-blank',
                    question: 'Complete: ____ nome = "João";',
                    correctAnswer: 'let',
                    explanation: 'let é usado para variáveis que podem mudar',
                    points: 15,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Por que evitar var?',
                    options: ['É muito lento', 'Tem escopo confuso', 'Não funciona mais', 'Ocupa mais memória'],
                    correctAnswer: 1,
                    explanation: 'var tem escopo de função, não de bloco, causando bugs',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Qual é válido como nome de variável?',
                    options: ['2nome', 'nome-completo', '_nome', 'nome completo'],
                    correctAnswer: 2,
                    explanation: 'Variáveis podem começar com _, $ ou letra, não número ou hífen',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'true-false',
                    question: 'const com objeto permite alterar propriedades do objeto',
                    correctAnswer: 'true',
                    explanation: 'const impede reatribuição, mas propriedades de objetos podem ser alteradas',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'fill-blank',
                    question: 'Complete: ____  PI = 3.14159; (não pode mudar)',
                    correctAnswer: 'const',
                    explanation: 'const é usado para valores que não devem mudar',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'multiple-choice',
                    question: 'Qual escopo tem let?',
                    options: ['Global', 'Função', 'Bloco', 'Módulo'],
                    correctAnswer: 2,
                    explanation: 'let tem escopo de bloco (dentro de { })',
                    points: 10,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'O que é hoisting?',
                    options: ['Erro de JS', 'Elevação de declarações', 'Tipo de loop', 'Função async'],
                    correctAnswer: 1,
                    explanation: 'Hoisting eleva declarações (var, function) ao topo do escopo',
                    points: 15,
                },
            ],
        },

        {
            id: 'operadores-js',
            title: 'Operadores em JavaScript',
            description: 'Aritméticos, comparação, lógicos e atribuição',
            xpReward: 150,
            estimatedTime: 25,
            content: {
                introduction: 'Operadores são símbolos que realizam operações em valores e variáveis. JavaScript tem vários tipos de operadores: aritméticos para cálculos, de atribuição para definir valores, de comparação para condições, e lógicos para combinar expressões. Dominar operadores é essencial para qualquer cálculo ou tomada de decisão no código.',
                sections: [
                    {
                        title: 'Operadores Aritméticos',
                        text: 'Operadores aritméticos realizam cálculos matemáticos. Além dos básicos (+, -, *, /), JavaScript tem módulo (%) que retorna o resto da divisão, e exponenciação (**) para potências. O operador + também concatena strings.',
                        code: '// Operações básicas\nlet soma = 10 + 5;        // 15\nlet subtracao = 10 - 5;   // 5\nlet multiplicacao = 10 * 5; // 50\nlet divisao = 10 / 5;     // 2\n\n// Módulo (resto da divisão)\nlet resto = 10 % 3;       // 1 (10 ÷ 3 = 3, resto 1)\nlet par = 8 % 2;          // 0 (número par!)\n\n// Exponenciação (potência)\nlet potencia = 2 ** 3;    // 8 (2³)\nlet raiz = 9 ** 0.5;      // 3 (raiz quadrada)\n\n// Concatenação de strings\nlet nome = "Ana" + " " + "Silva"; // "Ana Silva"',
                    },
                    {
                        title: 'Incremento e Decremento',
                        text: '++ aumenta o valor em 1, -- diminui em 1. Podem ser usados antes (pré) ou depois (pós) da variável. Pré-incremento retorna o novo valor, pós-incremento retorna o valor antigo.',
                        code: 'let x = 5;\n\n// Pós-incremento (retorna valor antigo, depois incrementa)\nconsole.log(x++);  // 5 (exibe 5, depois x vira 6)\nconsole.log(x);    // 6\n\n// Pré-incremento (incrementa primeiro, depois retorna)\nconsole.log(++x);  // 7 (incrementa para 7, exibe 7)\n\n// Decremento funciona igual\nlet y = 10;\nconsole.log(y--);  // 10 (exibe 10, depois y vira 9)\nconsole.log(--y);  // 8  (decrementa para 8, exibe 8)',
                    },
                    {
                        title: 'Operadores de Atribuição',
                        text: 'Operadores de atribuição definem ou modificam valores. O básico é =. Os compostos (+=, -=, *=, etc.) combinam operação + atribuição em um só passo, tornando o código mais conciso.',
                        code: 'let x = 10;        // atribuição básica\n\n// Atribuição composta\nx += 5;   // x = x + 5  → 15\nx -= 3;   // x = x - 3  → 12\nx *= 2;   // x = x * 2  → 24\nx /= 4;   // x = x / 4  → 6\nx %= 4;   // x = x % 4  → 2\nx **= 3;  // x = x ** 3 → 8\n\n// Útil para acumuladores\nlet total = 0;\ntotal += 100;  // 100\ntotal += 50;   // 150\ntotal += 25;   // 175',
                    },
                    {
                        title: 'Operadores de Comparação',
                        text: 'Operadores de comparação retornam true ou false. Use === (igualdade estrita) que compara valor E tipo. Evite == (igualdade frouxa) que faz conversão automática de tipos, causando resultados inesperados.',
                        code: '// Igualdade estrita (=== e !==) - RECOMENDADO\n5 === 5      // true (mesmo valor e tipo)\n5 === "5"    // false (número vs string)\n5 !== 3      // true (são diferentes)\n\n// Igualdade frouxa (== e !=) - EVITE\n5 == "5"     // true (converte tipos - perigoso!)\nnull == undefined // true (comportamento estranho)\n\n// Maior/Menor\n10 > 5       // true\n10 >= 10     // true\n5 < 10       // true\n5 <= 5       // true\n\n// Comparação de strings (ordem alfabética)\n"banana" > "abacaxi"  // true (b vem depois de a)',
                    },
                    {
                        title: 'Operadores Lógicos',
                        text: 'Operadores lógicos combinam expressões booleanas. && (AND) retorna true se AMBOS forem true. || (OR) retorna true se PELO MENOS UM for true. ! (NOT) inverte o valor. Muito usados em condicionais.',
                        code: '// AND (&&) - ambos devem ser true\nconst idade = 25;\nconst temCNH = true;\nconst podeAlugarCarro = idade >= 21 && temCNH; // true\n\n// OR (||) - pelo menos um true\nconst ehAdmin = false;\nconst ehModerador = true;\nconst temAcesso = ehAdmin || ehModerador; // true\n\n// NOT (!) - inverte\nconst logado = false;\nconst mostrarLogin = !logado; // true\n\n// Combinando operadores\nconst valido = (idade >= 18) && (temCNH || ehAdmin);\n\n// Short-circuit (atalho)\nconst nome = usuario && usuario.nome; // se usuario existir\nconst padrao = valor || "valor padrão"; // se valor for falsy',
                    },
                    {
                        title: 'Operador Ternário',
                        text: 'O operador ternário ( ? : ) é uma forma compacta de if-else. Sintaxe: condição ? valorSeTrue : valorSeFalse. Útil para atribuições simples baseadas em condição. Evite aninhar múltiplos ternários pois fica difícil de ler.',
                        code: '// Sintaxe: condição ? valorSeTrue : valorSeFalse\nconst idade = 20;\nconst status = idade >= 18 ? "adulto" : "menor";\nconsole.log(status); // "adulto"\n\n// Equivalente com if-else\nlet status2;\nif (idade >= 18) {\n  status2 = "adulto";\n} else {\n  status2 = "menor";\n}\n\n// Uso prático\nconst saudacao = hora < 12 ? "Bom dia" : "Boa tarde";\nconst plural = itens.length === 1 ? "item" : "itens";\nconst cor = ativo ? "green" : "gray";',
                    },
                    {
                        title: 'Precedência de Operadores',
                        text: 'Precedência define a ordem de execução. Parênteses têm maior prioridade. Depois: !, ++/--, **, */%, +-, comparações, &&, ||, ternário, atribuição. Use parênteses para deixar a intenção clara.',
                        code: '// Precedência padrão\nlet resultado = 2 + 3 * 4;   // 14 (não 20!)\n// * executa antes de +\n\n// Use parênteses para clareza\nlet correto = (2 + 3) * 4;   // 20\n\n// Ordem: ! > && > ||\nconst a = true || false && false; // true\n// Equivale a: true || (false && false)\n\n// Melhor com parênteses\nconst b = (true || false) && false; // false\n\n// Prática recomendada\nconst aprovado = (nota >= 7) && (frequencia >= 75);\nconst desconto = (ehVIP || temCupom) && (total > 100);',
                    },
                ],
                tips: [
                    'Sempre use === ao invés de == para comparações',
                    'Use parênteses para deixar a precedência clara',
                    'Operadores compostos (+=) tornam o código mais limpo',
                    'Cuidado com ternários aninhados - prefira if-else',
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual é o resultado de 10 % 3?',
                    options: ['3', '1', '3.33', '10'],
                    correctAnswer: 1,
                    explanation: '% retorna o resto da divisão. 10 ÷ 3 = 3, resto 1',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Qual operador é recomendado para comparar igualdade?',
                    options: ['=', '==', '===', '=>'],
                    correctAnswer: 2,
                    explanation: '=== compara valor E tipo, evitando conversões automáticas',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'true-false',
                    question: '5 === "5" retorna true',
                    correctAnswer: 'false',
                    explanation: '=== compara tipo também. 5 (number) !== "5" (string)',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'fill-blank',
                    question: 'Complete: let x = 10; x ____ 5; // x agora é 15',
                    correctAnswer: '+=',
                    explanation: '+= adiciona e atribui: x = x + 5',
                    points: 15,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual é o resultado de true && false?',
                    options: ['true', 'false', 'null', 'undefined'],
                    correctAnswer: 1,
                    explanation: 'AND (&&) só é true se AMBOS forem true',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Qual é o resultado de true || false?',
                    options: ['true', 'false', 'null', 'undefined'],
                    correctAnswer: 0,
                    explanation: 'OR (||) é true se PELO MENOS UM for true',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'fill-blank',
                    question: 'Complete: idade >= 18 ____ "adulto" : "menor"',
                    correctAnswer: '?',
                    explanation: 'O operador ternário usa ? para separar condição do valor se true',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'multiple-choice',
                    question: 'Qual é o resultado de 2 + 3 * 4?',
                    options: ['20', '14', '24', '9'],
                    correctAnswer: 1,
                    explanation: '* tem maior precedência que +, então 3*4=12, depois 2+12=14',
                    points: 10,
                },
                {
                    id: 'q9',
                    type: 'true-false',
                    question: '!true retorna false',
                    correctAnswer: 'true',
                    explanation: 'O operador ! (NOT) inverte o valor booleano',
                    points: 10,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'Qual operador calcula potência?',
                    options: ['^', '**', 'pow', '^^'],
                    correctAnswer: 1,
                    explanation: '** é o operador de exponenciação: 2**3 = 8',
                    points: 15,
                },
            ],
        },

    ],
};

// ============================================
// MÓDULO 2: TIPOS DE DADOS
// ============================================

export const JS_TIPOS: LearningModule = {
    id: 'js-tipos',
    name: 'Tipos de Dados',
    description: 'Strings, numbers, booleans, arrays e objetos',
    icon: '📊',
    difficulty: 'beginner',
    requiredXP: 200,
    lessons: [
        {
            id: 'tipos-primitivos',
            title: 'Tipos Primitivos',
            description: 'String, Number, Boolean, null, undefined',
            xpReward: 100,
            estimatedTime: 15,
            content: {
                introduction: 'JavaScript tem tipos primitivos que são imutáveis e tipos de referência como objetos.',
                sections: [
                    {
                        title: 'String',
                        text: 'Texto entre aspas simples, duplas ou crases (template literals).',
                        code: 'let nome = "Maria";\nlet sobrenome = \'Silva\';\nlet completo = `${nome} ${sobrenome}`; // Template literal',
                    },
                    {
                        title: 'Number',
                        text: 'JavaScript tem apenas um tipo numérico que inclui inteiros e decimais.',
                        code: 'let idade = 25;\nlet preco = 19.99;\nlet infinito = Infinity;\nlet naoNumero = NaN; // Not a Number',
                    },
                    {
                        title: 'Boolean',
                        text: 'Verdadeiro ou falso, usado em condições.',
                        code: 'let ativo = true;\nlet logado = false;\nlet maior = 10 > 5; // true',
                    },
                    {
                        title: 'null e undefined',
                        text: 'null: ausência intencional. undefined: não definido.',
                        code: 'let vazio = null; // intencionalmente vazio\nlet indefinido; // undefined\nconsole.log(indefinido); // undefined',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual é a sintaxe de template literal?',
                    options: ['"texto"', "'texto'", '`texto`', '<texto>'],
                    correctAnswer: 2,
                    explanation: 'Template literals usam crases (backticks): `texto`',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que é NaN?',
                    options: ['Número negativo', 'Not a Number', 'Null and Nothing', 'Número alto'],
                    correctAnswer: 1,
                    explanation: 'NaN significa "Not a Number" - resultado de operações numéricas inválidas',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: let ativo = ____;',
                    correctAnswer: 'true',
                    explanation: 'Boolean usa true ou false',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'null e undefined são a mesma coisa',
                    correctAnswer: 'false',
                    explanation: 'null é intencional, undefined é ausência de valor',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Como inserir variável em template literal?',
                    options: ['#{var}', '${var}', '%{var}', '@{var}'],
                    correctAnswer: 1,
                    explanation: 'Template literals usam ${variavel} para interpolação',
                    points: 10,
                },
            ],
        },
        {
            id: 'arrays-js',
            title: 'Arrays',
            description: 'Listas ordenadas de valores',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Arrays armazenam múltiplos valores em uma única variável.',
                sections: [
                    {
                        title: 'Criando Arrays',
                        text: 'Arrays são listas ordenadas, começando do índice 0.',
                        code: 'let frutas = ["maçã", "banana", "laranja"];\nlet numeros = [1, 2, 3, 4, 5];\nlet misto = [1, "dois", true, null];',
                    },
                    {
                        title: 'Acessando Elementos',
                        text: 'Use índices para acessar elementos. Índices começam em 0.',
                        code: 'let frutas = ["maçã", "banana", "laranja"];\nconsole.log(frutas[0]); // "maçã"\nconsole.log(frutas[2]); // "laranja"\nconsole.log(frutas.length); // 3',
                    },
                    {
                        title: 'Métodos Básicos',
                        text: 'push adiciona ao final, pop remove do final.',
                        code: 'let lista = [1, 2, 3];\nlista.push(4); // [1, 2, 3, 4]\nlista.pop(); // [1, 2, 3]\nlista.unshift(0); // [0, 1, 2, 3]',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual é o índice do primeiro elemento de um array?',
                    options: ['1', '0', '-1', 'primeiro'],
                    correctAnswer: 1,
                    explanation: 'Arrays começam no índice 0',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'Qual método adiciona elemento ao final?',
                    options: ['add()', 'push()', 'append()', 'insert()'],
                    correctAnswer: 1,
                    explanation: 'push() adiciona ao final do array',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: let frutas = ["maçã"]; frutas.____("banana");',
                    correctAnswer: 'push',
                    explanation: 'push adiciona ao final do array',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'Arrays podem conter tipos diferentes',
                    correctAnswer: 'true',
                    explanation: 'JS permite arrays com tipos mistos',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'O que array.length retorna?',
                    options: ['Último elemento', 'Primeiro elemento', 'Número de elementos', 'Índice máximo'],
                    correctAnswer: 2,
                    explanation: 'length retorna a quantidade de elementos',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Qual método remove o último elemento?',
                    options: ['remove()', 'delete()', 'pop()', 'shift()'],
                    correctAnswer: 2,
                    explanation: 'pop() remove e retorna o último elemento',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'multiple-choice',
                    question: 'Qual método remove o primeiro elemento?',
                    options: ['pop()', 'shift()', 'unshift()', 'first()'],
                    correctAnswer: 1,
                    explanation: 'shift() remove o primeiro elemento do array',
                    points: 10,
                },
                {
                    id: 'q8',
                    type: 'fill-blank',
                    question: 'Complete: let arr = [1,2,3]; arr.____; // tamanho',
                    correctAnswer: 'length',
                    explanation: 'length é a propriedade que retorna o tamanho',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'true-false',
                    question: 'arr[arr.length] acessa o último elemento',
                    correctAnswer: 'false',
                    explanation: 'O último índice é arr.length - 1, não arr.length',
                    points: 15,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'O que unshift() faz?',
                    options: ['Remove do início', 'Adiciona ao início', 'Ordena array', 'Inverte array'],
                    correctAnswer: 1,
                    explanation: 'unshift() adiciona elementos no início do array',
                    points: 10,
                },
            ],
        },

    ],
};

// ============================================
// MÓDULO 3: CONTROLE DE FLUXO
// ============================================

export const JS_CONTROLE: LearningModule = {
    id: 'js-controle',
    name: 'Controle de Fluxo',
    description: 'Condicionais e loops',
    icon: '🔀',
    difficulty: 'intermediate',
    requiredXP: 400,
    lessons: [
        {
            id: 'condicionais-js',
            title: 'Condicionais',
            description: 'if, else, else if e operador ternário',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Condicionais permitem executar código baseado em condições.',
                sections: [
                    {
                        title: 'if e else',
                        text: 'if executa código se a condição for verdadeira.',
                        code: 'let idade = 18;\n\nif (idade >= 18) {\n  console.log("Maior de idade");\n} else {\n  console.log("Menor de idade");\n}',
                    },
                    {
                        title: 'else if',
                        text: 'Para múltiplas condições.',
                        code: 'let nota = 75;\n\nif (nota >= 90) {\n  console.log("A");\n} else if (nota >= 70) {\n  console.log("B");\n} else {\n  console.log("C");\n}',
                    },
                    {
                        title: 'Operador Ternário',
                        text: 'Forma curta de if/else.',
                        code: 'let idade = 20;\nlet status = idade >= 18 ? "adulto" : "menor";\nconsole.log(status); // "adulto"',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual operador verifica igualdade estrita?',
                    options: ['==', '===', '=', '!='],
                    correctAnswer: 1,
                    explanation: '=== compara valor E tipo (estrito)',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que o operador ternário faz?',
                    options: ['Loop 3 vezes', 'if/else curto', 'Declara 3 variáveis', 'Compara 3 valores'],
                    correctAnswer: 1,
                    explanation: 'Ternário: condição ? seVerdade : seFalso',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: if (x > 10) { } ____ { }',
                    correctAnswer: 'else',
                    explanation: 'else é executado quando if é falso',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: '== e === são equivalentes',
                    correctAnswer: 'false',
                    explanation: '== permite coerção, === é estrito (valor e tipo)',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual é a sintaxe do operador ternário?',
                    options: ['if ? then : else', 'condição ? verdade : falso', 'check(cond, v, f)', 'cond && v || f'],
                    correctAnswer: 1,
                    explanation: 'Ternário: condição ? valorSeVerdade : valorSeFalso',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'O que "1" == 1 retorna?',
                    options: ['true', 'false', 'undefined', 'erro'],
                    correctAnswer: 0,
                    explanation: '== faz coerção de tipo, então "1" == 1 é true',
                    points: 15,
                },
                {
                    id: 'q7',
                    type: 'multiple-choice',
                    question: 'O que "1" === 1 retorna?',
                    options: ['true', 'false', 'undefined', 'erro'],
                    correctAnswer: 1,
                    explanation: '=== compara tipo também, string !== number',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'fill-blank',
                    question: 'Complete: let x = a > b ____ a : b; (maior valor)',
                    correctAnswer: '?',
                    explanation: 'Operador ternário: condição ? valor1 : valor2',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'true-false',
                    question: 'switch pode usar strings como case',
                    correctAnswer: 'true',
                    explanation: 'switch funciona com strings, números e outros tipos',
                    points: 10,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'O que && representa?',
                    options: ['OU lógico', 'E lógico', 'Negação', 'Igual'],
                    correctAnswer: 1,
                    explanation: '&& é AND lógico - ambas condições devem ser verdadeiras',
                    points: 10,
                },
            ],
        },

        {
            id: 'loops-js',
            title: 'Loops',
            description: 'for, while e forEach',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Loops repetem código múltiplas vezes.',
                sections: [
                    {
                        title: 'for',
                        text: 'Loop clássico com contador.',
                        code: 'for (let i = 0; i < 5; i++) {\n  console.log(i); // 0, 1, 2, 3, 4\n}',
                    },
                    {
                        title: 'while',
                        text: 'Repete enquanto condição for verdadeira.',
                        code: 'let i = 0;\nwhile (i < 5) {\n  console.log(i);\n  i++;\n}',
                    },
                    {
                        title: 'for...of',
                        text: 'Itera sobre valores de arrays.',
                        code: 'let frutas = ["maçã", "banana", "laranja"];\nfor (let fruta of frutas) {\n  console.log(fruta);\n}',
                    },
                    {
                        title: 'forEach',
                        text: 'Método de array para iterar.',
                        code: 'let numeros = [1, 2, 3];\nnumeros.forEach(num => {\n  console.log(num * 2);\n});',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual loop é melhor para arrays?',
                    options: ['for clássico', 'while', 'for...of ou forEach', 'do...while'],
                    correctAnswer: 2,
                    explanation: 'for...of e forEach são mais limpos para arrays',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que i++ faz?',
                    options: ['Dobra i', 'Incrementa i em 1', 'Reseta i', 'Declara i'],
                    correctAnswer: 1,
                    explanation: 'i++ é equivalente a i = i + 1',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: for (let i = 0; i < 10; i____)',
                    correctAnswer: '++',
                    explanation: '++ incrementa a variável em 1',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'while pode criar loops infinitos',
                    correctAnswer: 'true',
                    explanation: 'Se a condição nunca se tornar falsa, o loop é infinito',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual comando sai do loop imediatamente?',
                    options: ['stop', 'exit', 'break', 'return'],
                    correctAnswer: 2,
                    explanation: 'break sai do loop atual',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'O que continue faz?',
                    options: ['Sai do loop', 'Pula para próxima iteração', 'Reinicia loop', 'Pausa loop'],
                    correctAnswer: 1,
                    explanation: 'continue pula para a próxima iteração do loop',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'multiple-choice',
                    question: 'for...in itera sobre:',
                    options: ['Valores', 'Índices/chaves', 'Métodos', 'Tipos'],
                    correctAnswer: 1,
                    explanation: 'for...in itera sobre chaves/índices do objeto',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'fill-blank',
                    question: 'Complete: for (let item ____ array) { }',
                    correctAnswer: 'of',
                    explanation: 'for...of itera sobre valores do array',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'true-false',
                    question: 'forEach retorna um novo array',
                    correctAnswer: 'false',
                    explanation: 'forEach não retorna nada. Use map para retornar array',
                    points: 10,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'Qual a diferença entre for...in e for...of?',
                    options: ['São iguais', 'in = chaves, of = valores', 'of = chaves, in = valores', 'Só sintaxe'],
                    correctAnswer: 1,
                    explanation: 'for...in itera chaves, for...of itera valores',
                    points: 15,
                },
            ],
        },

    ],
};

// ============================================
// MÓDULO 4: FUNÇÕES
// ============================================

export const JS_FUNCOES: LearningModule = {
    id: 'js-funcoes',
    name: 'Funções',
    description: 'Declaração, parâmetros e arrow functions',
    icon: '🔧',
    difficulty: 'intermediate',
    requiredXP: 600,
    lessons: [
        {
            id: 'funcoes-basicas',
            title: 'Funções Básicas',
            description: 'Declarando e chamando funções',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Funções são blocos de código reutilizáveis.',
                sections: [
                    {
                        title: 'Declarando Funções',
                        text: 'Use function para declarar uma função.',
                        code: 'function saudacao(nome) {\n  return "Olá, " + nome + "!";\n}\n\nconsole.log(saudacao("Maria")); // "Olá, Maria!"',
                    },
                    {
                        title: 'Parâmetros e Retorno',
                        text: 'Funções recebem parâmetros e retornam valores.',
                        code: 'function soma(a, b) {\n  return a + b;\n}\n\nlet resultado = soma(5, 3); // 8',
                    },
                    {
                        title: 'Parâmetros Padrão',
                        text: 'Defina valores padrão para parâmetros.',
                        code: 'function saudar(nome = "Visitante") {\n  return "Olá, " + nome;\n}\n\nsaudar(); // "Olá, Visitante"\nsaudar("Ana"); // "Olá, Ana"',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual palavra-chave declara uma função?',
                    options: ['func', 'function', 'def', 'fn'],
                    correctAnswer: 1,
                    explanation: 'function é a palavra-chave para declarar funções',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que return faz em uma função?',
                    options: ['Imprime valor', 'Retorna valor e encerra', 'Declara variável', 'Inicia loop'],
                    correctAnswer: 1,
                    explanation: 'return retorna um valor e encerra a função',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: function soma(a, b) { ____ a + b; }',
                    correctAnswer: 'return',
                    explanation: 'return retorna o resultado da função',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'Funções podem ter parâmetros com valores padrão',
                    correctAnswer: 'true',
                    explanation: 'Parâmetros padrão são definidos com = na declaração',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Como chamar a função saudacao("João")?',
                    options: ['call saudacao("João")', 'saudacao("João")', 'run saudacao("João")', 'saudacao: "João"'],
                    correctAnswer: 1,
                    explanation: 'Funções são chamadas pelo nome seguido de ()',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'O que é uma função anônima?',
                    options: ['Função sem código', 'Função sem nome', 'Função privada', 'Função vazia'],
                    correctAnswer: 1,
                    explanation: 'Função anônima não tem nome, usada como valor',
                    points: 10,
                },
                {
                    id: 'q7',
                    type: 'true-false',
                    question: 'Uma função sem return retorna undefined',
                    correctAnswer: 'true',
                    explanation: 'Funções sem return explícito retornam undefined',
                    points: 15,
                },
                {
                    id: 'q8',
                    type: 'fill-blank',
                    question: 'Complete: const fn = ____(a) { return a * 2; }',
                    correctAnswer: 'function',
                    explanation: 'Expressão de função usando function',
                    points: 15,
                },
                {
                    id: 'q9',
                    type: 'multiple-choice',
                    question: 'Qual é o escopo de parâmetros de função?',
                    options: ['Global', 'Local à função', 'Bloco', 'Módulo'],
                    correctAnswer: 1,
                    explanation: 'Parâmetros só existem dentro da função',
                    points: 10,
                },
                {
                    id: 'q10',
                    type: 'multiple-choice',
                    question: 'O que é recursão?',
                    options: ['Loop infinito', 'Função que chama a si mesma', 'Função sem parâmetros', 'Erro de JS'],
                    correctAnswer: 1,
                    explanation: 'Recursão é quando uma função chama a si mesma',
                    points: 15,
                },
            ],
        },

        {
            id: 'arrow-functions',
            title: 'Arrow Functions',
            description: 'Sintaxe moderna e concisa para funções',
            xpReward: 100,
            estimatedTime: 15,
            content: {
                introduction: 'Arrow functions são uma forma mais curta de escrever funções.',
                sections: [
                    {
                        title: 'Sintaxe Arrow',
                        text: 'Use => para criar arrow functions.',
                        code: 'const soma = (a, b) => a + b;\nconst dobro = n => n * 2;\nconst saudar = () => "Olá!";',
                    },
                    {
                        title: 'Com Bloco',
                        text: 'Para múltiplas linhas, use chaves e return.',
                        code: 'const calcular = (a, b) => {\n  const resultado = a + b;\n  return resultado * 2;\n};',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual é a sintaxe de arrow function?',
                    options: ['function =>', '() ->', '() =>', '=> ()'],
                    correctAnswer: 2,
                    explanation: 'Arrow functions usam () => { }',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'fill-blank',
                    question: 'Complete: const dobro = n ____ n * 2;',
                    correctAnswer: '=>',
                    explanation: '=> é o operador arrow function',
                    points: 15,
                },
                {
                    id: 'q3',
                    type: 'true-false',
                    question: 'Arrow functions com uma expressão precisam de return',
                    correctAnswer: 'false',
                    explanation: 'Return é implícito para expressões simples',
                    points: 10,
                },
                {
                    id: 'q4',
                    type: 'multiple-choice',
                    question: 'Quando usar chaves {} em arrow functions?',
                    options: ['Sempre', 'Nunca', 'Com múltiplas linhas', 'Só com parâmetros'],
                    correctAnswer: 2,
                    explanation: 'Chaves são necessárias para múltiplas linhas de código',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'const x = n => n * 2. Quantos parênteses são necessários?',
                    options: ['Nenhum (um parâmetro)', 'Dois sempre', 'Quatro', 'Depende do navegador'],
                    correctAnswer: 0,
                    explanation: 'Com um parâmetro, parênteses são opcionais',
                    points: 10,
                },
            ],
        },
    ],
};

// ============================================
// MÓDULO 5: DOM E EVENTOS
// ============================================

export const JS_DOM: LearningModule = {
    id: 'js-dom',
    name: 'DOM e Eventos',
    description: 'Manipule a página e responda a ações do usuário',
    icon: '🖱️',
    difficulty: 'intermediate',
    requiredXP: 800,
    lessons: [
        {
            id: 'selecionando-dom',
            title: 'Selecionando Elementos',
            description: 'querySelector, getElementById e mais',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'O DOM (Document Object Model) é a representação da página HTML como objetos JavaScript.',
                sections: [
                    {
                        title: 'querySelector',
                        text: 'Seleciona o primeiro elemento que corresponde ao seletor CSS.',
                        code: 'const titulo = document.querySelector("h1");\nconst botao = document.querySelector(".btn");\nconst form = document.querySelector("#formulario");',
                    },
                    {
                        title: 'querySelectorAll',
                        text: 'Seleciona todos os elementos correspondentes.',
                        code: 'const paragrafos = document.querySelectorAll("p");\nparagrafos.forEach(p => {\n  console.log(p.textContent);\n});',
                    },
                    {
                        title: 'Métodos Clássicos',
                        text: 'getElementById e getElementsByClassName.',
                        code: 'const header = document.getElementById("header");\nconst cards = document.getElementsByClassName("card");',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual método seleciona por seletor CSS?',
                    options: ['getElement()', 'querySelector()', 'select()', 'find()'],
                    correctAnswer: 1,
                    explanation: 'querySelector aceita qualquer seletor CSS',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que DOM significa?',
                    options: ['Document Object Model', 'Data Object Method', 'Direct Output Mode', 'Document Order Manager'],
                    correctAnswer: 0,
                    explanation: 'DOM = Document Object Model',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: document.____("#menu")',
                    correctAnswer: 'querySelector',
                    explanation: 'querySelector seleciona elementos por seletor CSS',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'querySelectorAll retorna um array',
                    correctAnswer: 'false',
                    explanation: 'Retorna NodeList, semelhante mas não idêntico a array',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Como selecionar elemento por ID com getElementById?',
                    options: ['getElementById("#id")', 'getElementById("id")', 'getElementById(".id")', 'getElementById(id)'],
                    correctAnswer: 1,
                    explanation: 'getElementById recebe apenas o nome do ID, sem #',
                    points: 10,
                },
            ],
        },
        {
            id: 'eventos-js',
            title: 'Eventos',
            description: 'Responda a cliques, teclas e mais',
            xpReward: 150,
            estimatedTime: 20,
            content: {
                introduction: 'Eventos permitem que seu código responda às ações do usuário.',
                sections: [
                    {
                        title: 'addEventListener',
                        text: 'Adiciona um listener de evento a um elemento.',
                        code: 'const botao = document.querySelector("button");\n\nbotao.addEventListener("click", () => {\n  alert("Clicado!");\n});',
                    },
                    {
                        title: 'Eventos Comuns',
                        text: 'click, submit, keydown, mouseover, change, load.',
                        code: 'form.addEventListener("submit", (e) => {\n  e.preventDefault();\n  console.log("Formulário enviado");\n});\n\ninput.addEventListener("change", (e) => {\n  console.log(e.target.value);\n});',
                    },
                    {
                        title: 'Objeto Event',
                        text: 'O evento contém informações sobre a ação.',
                        code: 'document.addEventListener("keydown", (e) => {\n  console.log("Tecla:", e.key);\n  console.log("Código:", e.code);\n});',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Qual método adiciona evento a um elemento?',
                    options: ['on()', 'addEvent()', 'addEventListener()', 'bind()'],
                    correctAnswer: 2,
                    explanation: 'addEventListener é o método padrão para eventos',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que e.preventDefault() faz?',
                    options: ['Previne o comportamento padrão', 'Previne erros', 'Para a execução', 'Previne duplicação'],
                    correctAnswer: 0,
                    explanation: 'preventDefault impede a ação padrão do evento',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: btn.addEventListener("____", handler)',
                    correctAnswer: 'click',
                    explanation: 'click é o evento de clique do mouse',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'e.target retorna o elemento que disparou o evento',
                    correctAnswer: 'true',
                    explanation: 'e.target é o elemento onde o evento ocorreu',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Qual evento é disparado ao enviar formulário?',
                    options: ['click', 'send', 'submit', 'post'],
                    correctAnswer: 2,
                    explanation: 'submit é o evento de envio de formulário',
                    points: 10,
                },
                {
                    id: 'q6',
                    type: 'multiple-choice',
                    question: 'Como obter o valor de um input no evento?',
                    options: ['e.value', 'e.target.value', 'e.input.value', 'e.text'],
                    correctAnswer: 1,
                    explanation: 'e.target.value acessa o valor do input',
                    points: 10,
                },
            ],
        },
    ],
};

// ============================================
// MÓDULO 6: OBJETOS E MÉTODOS MODERNOS
// ============================================

export const JS_OBJETOS: LearningModule = {
    id: 'js-objetos',
    name: 'Objetos JavaScript',
    description: 'Objetos, métodos e desestruturação',
    icon: '📦',
    difficulty: 'advanced',
    requiredXP: 1000,
    lessons: [
        {
            id: 'objetos-basicos',
            title: 'Objetos',
            description: 'Criando e manipulando objetos',
            xpReward: 120,
            estimatedTime: 18,
            content: {
                introduction: 'Objetos armazenam dados em pares chave-valor.',
                sections: [
                    {
                        title: 'Criando Objetos',
                        text: 'Use chaves {} para criar objetos.',
                        code: 'const pessoa = {\n  nome: "Maria",\n  idade: 30,\n  email: "maria@email.com"\n};',
                    },
                    {
                        title: 'Acessando Propriedades',
                        text: 'Use ponto ou colchetes para acessar.',
                        code: 'console.log(pessoa.nome); // "Maria"\nconsole.log(pessoa["idade"]); // 30\n\npessoa.cidade = "São Paulo"; // adiciona',
                    },
                    {
                        title: 'Métodos',
                        text: 'Objetos podem ter funções como propriedades.',
                        code: 'const usuario = {\n  nome: "João",\n  saudar() {\n    return `Olá, sou ${this.nome}`;\n  }\n};\n\nconsole.log(usuario.saudar());',
                    },
                ],
            },
            quiz: [
                {
                    id: 'q1',
                    type: 'multiple-choice',
                    question: 'Como acessar propriedade "nome" de um objeto?',
                    options: ['objeto->nome', 'objeto.nome', 'objeto:nome', 'objeto(nome)'],
                    correctAnswer: 1,
                    explanation: 'Use ponto (.) para acessar propriedades',
                    points: 10,
                },
                {
                    id: 'q2',
                    type: 'multiple-choice',
                    question: 'O que "this" representa dentro de um método?',
                    options: ['A função', 'O objeto', 'O documento', 'O window'],
                    correctAnswer: 1,
                    explanation: 'this referencia o objeto que contém o método',
                    points: 10,
                },
                {
                    id: 'q3',
                    type: 'fill-blank',
                    question: 'Complete: const obj = { nome: "Ana", ____: 25 };',
                    correctAnswer: 'idade',
                    explanation: 'Propriedades são pares chave: valor',
                    points: 15,
                },
                {
                    id: 'q4',
                    type: 'true-false',
                    question: 'Objetos são mutáveis mesmo com const',
                    correctAnswer: 'true',
                    explanation: 'const impede reatribuição, não mutação',
                    points: 10,
                },
                {
                    id: 'q5',
                    type: 'multiple-choice',
                    question: 'Como adicionar propriedade a objeto existente?',
                    options: ['objeto.add("prop", valor)', 'objeto.prop = valor', 'objeto += prop', 'objeto.push(prop)'],
                    correctAnswer: 1,
                    explanation: 'objeto.propriedade = valor adiciona/modifica',
                    points: 10,
                },
            ],
        },
    ],
};

// ============================================
// EXPORTAÇÃO DOS MÓDULOS JAVASCRIPT
// ============================================

export const JS_MODULES: LearningModule[] = [
    JS_FUNDAMENTOS,
    JS_TIPOS,
    JS_CONTROLE,
    JS_FUNCOES,
    JS_DOM,
    JS_OBJETOS,
];
