// CodeQuest - Expanded Questions (Part 4: Media & Advanced)
import type { QuizQuestion } from './lessons';

export const MEDIA_VIDEO_QUESTIONS: QuizQuestion[] = [
    {
        id: 'video-1',
        type: 'multiple-choice',
        question: 'Qual atributo exibe os controles do player?',
        options: ['player', 'controls', 'buttons', 'ui'],
        correctAnswer: 1,
        explanation: 'controls exibe play, pause, volume e outros controles',
        points: 10,
    },
    {
        id: 'video-2',
        type: 'multiple-choice',
        question: 'Qual atributo inicia o vídeo automaticamente?',
        options: ['auto', 'autoplay', 'autostart', 'play'],
        correctAnswer: 1,
        explanation: 'autoplay inicia a reprodução automaticamente',
        points: 10,
    },
    {
        id: 'video-3',
        type: 'multiple-choice',
        question: 'Qual atributo repete o vídeo infinitamente?',
        options: ['repeat', 'loop', 'infinite', 'replay'],
        correctAnswer: 1,
        explanation: 'loop faz o vídeo repetir quando termina',
        points: 10,
    },
    {
        id: 'video-4',
        type: 'multiple-choice',
        question: 'Qual atributo silencia o vídeo?',
        options: ['silent', 'muted', 'nosound', 'quiet'],
        correctAnswer: 1,
        explanation: 'muted remove o áudio do vídeo',
        points: 10,
    },
    {
        id: 'video-5',
        type: 'multiple-choice',
        question: 'Para que serve o atributo poster?',
        options: ['Define título', 'Imagem de preview', 'Descrição', 'Tamanho'],
        correctAnswer: 1,
        explanation: 'poster define a imagem exibida antes de reproduzir',
        points: 10,
    },
];

export const MEDIA_SVG_QUESTIONS: QuizQuestion[] = [
    {
        id: 'svg-1',
        type: 'multiple-choice',
        question: 'O que significa SVG?',
        options: ['Super Vector Graphics', 'Scalable Vector Graphics', 'Simple Visual Graphics', 'Standard Vector Graphics'],
        correctAnswer: 1,
        explanation: 'SVG = Scalable Vector Graphics',
        points: 10,
    },
    {
        id: 'svg-2',
        type: 'multiple-choice',
        question: 'Qual tag cria um círculo em SVG?',
        options: ['<round>', '<circle>', '<oval>', '<sphere>'],
        correctAnswer: 1,
        explanation: '<circle> cria círculos em SVG',
        points: 10,
    },
    {
        id: 'svg-3',
        type: 'multiple-choice',
        question: 'Qual atributo define a cor de preenchimento?',
        options: ['color', 'fill', 'background', 'paint'],
        correctAnswer: 1,
        explanation: 'fill define a cor de preenchimento em SVG',
        points: 10,
    },
    {
        id: 'svg-4',
        type: 'multiple-choice',
        question: 'Qual tag cria um retângulo?',
        options: ['<box>', '<rect>', '<square>', '<rectangle>'],
        correctAnswer: 1,
        explanation: '<rect> cria retângulos em SVG',
        points: 10,
    },
    {
        id: 'svg-5',
        type: 'multiple-choice',
        question: 'SVG perde qualidade ao aumentar?',
        options: ['Sim', 'Não', 'Depende', 'Às vezes'],
        correctAnswer: 1,
        explanation: 'SVG é vetorial e não perde qualidade ao escalar',
        points: 10,
    },
];

export const ADVANCED_CANVAS_QUESTIONS: QuizQuestion[] = [
    {
        id: 'canvas-1',
        type: 'multiple-choice',
        question: 'Qual método obtém o contexto de desenho?',
        options: ['getContext("2d")', 'getDrawing()', 'get2D()', 'context()'],
        correctAnswer: 0,
        explanation: 'canvas.getContext("2d") retorna o contexto 2D',
        points: 10,
    },
    {
        id: 'canvas-2',
        type: 'multiple-choice',
        question: 'Qual método desenha um retângulo preenchido?',
        options: ['drawRect()', 'fillRect()', 'rect()', 'paintRect()'],
        correctAnswer: 1,
        explanation: 'fillRect(x, y, width, height) desenha retângulo preenchido',
        points: 10,
    },
    {
        id: 'canvas-3',
        type: 'multiple-choice',
        question: 'Canvas usa qual linguagem para desenhar?',
        options: ['CSS', 'HTML', 'JavaScript', 'SVG'],
        correctAnswer: 2,
        explanation: 'Canvas é manipulado via JavaScript',
        points: 10,
    },
    {
        id: 'canvas-4',
        type: 'multiple-choice',
        question: 'Qual propriedade define a cor de preenchimento?',
        options: ['color', 'fillColor', 'fillStyle', 'paintColor'],
        correctAnswer: 2,
        explanation: 'ctx.fillStyle define a cor de preenchimento',
        points: 10,
    },
    {
        id: 'canvas-5',
        type: 'multiple-choice',
        question: 'Como iniciar um novo caminho em Canvas?',
        options: ['newPath()', 'beginPath()', 'startPath()', 'path()'],
        correctAnswer: 1,
        explanation: 'beginPath() inicia um novo caminho',
        points: 10,
    },
];

export const ADVANCED_STORAGE_QUESTIONS: QuizQuestion[] = [
    {
        id: 'storage-1',
        type: 'multiple-choice',
        question: 'Qual storage persiste após fechar o navegador?',
        options: ['sessionStorage', 'tempStorage', 'localStorage', 'cacheStorage'],
        correctAnswer: 2,
        explanation: 'localStorage persiste indefinidamente',
        points: 10,
    },
    {
        id: 'storage-2',
        type: 'multiple-choice',
        question: 'Qual método salva dados no storage?',
        options: ['set()', 'save()', 'setItem()', 'store()'],
        correctAnswer: 2,
        explanation: 'setItem(key, value) salva dados',
        points: 10,
    },
    {
        id: 'storage-3',
        type: 'multiple-choice',
        question: 'Qual método lê dados do storage?',
        options: ['get()', 'read()', 'getItem()', 'load()'],
        correctAnswer: 2,
        explanation: 'getItem(key) retorna o valor armazenado',
        points: 10,
    },
    {
        id: 'storage-4',
        type: 'multiple-choice',
        question: 'Como armazenar objetos no localStorage?',
        options: ['Diretamente', 'JSON.stringify()', 'toString()', 'Não é possível'],
        correctAnswer: 1,
        explanation: 'Objetos devem ser convertidos com JSON.stringify()',
        points: 10,
    },
    {
        id: 'storage-5',
        type: 'multiple-choice',
        question: 'sessionStorage é apagado quando?',
        options: ['Nunca', 'Ao fechar aba', 'Diariamente', 'Semanalmente'],
        correctAnswer: 1,
        explanation: 'sessionStorage é apagado ao fechar a aba/janela',
        points: 10,
    },
];

// Export all question banks for easy import
export const ALL_QUESTION_BANKS = {
    video: MEDIA_VIDEO_QUESTIONS,
    svg: MEDIA_SVG_QUESTIONS,
    canvas: ADVANCED_CANVAS_QUESTIONS,
    storage: ADVANCED_STORAGE_QUESTIONS,
};
