// CodeQuest - Expanded Questions (Part 2: Links, Images, Structure)
import type { QuizQuestion } from './lessons';

export const BASICS_LINKS_QUESTIONS: QuizQuestion[] = [
    {
        id: 'link-1',
        type: 'multiple-choice',
        question: 'Qual atributo faz o link abrir em nova aba?',
        options: ['new="_blank"', 'target="_blank"', 'open="new"', 'href="_new"'],
        correctAnswer: 1,
        explanation: 'target="_blank" abre o link em uma nova aba do navegador',
        points: 10,
    },
    {
        id: 'link-2',
        type: 'multiple-choice',
        question: 'Como criar um link para email?',
        options: ['href="email:..."', 'href="mail:..."', 'href="mailto:..."', 'href="@..."'],
        correctAnswer: 2,
        explanation: 'mailto: é o protocolo para links de email',
        points: 10,
    },
    {
        id: 'link-3',
        type: 'multiple-choice',
        question: 'Qual tag cria um hyperlink?',
        options: ['<link>', '<a>', '<href>', '<url>'],
        correctAnswer: 1,
        explanation: '<a> (anchor) é a tag para criar links',
        points: 10,
    },
    {
        id: 'link-4',
        type: 'multiple-choice',
        question: 'O que significa href?',
        options: ['Hypertext Reference', 'High Reference', 'HTML Reference', 'Header Reference'],
        correctAnswer: 0,
        explanation: 'href = Hypertext Reference (Referência de Hipertexto)',
        points: 10,
    },
    {
        id: 'link-5',
        type: 'multiple-choice',
        question: 'Como criar um link para telefone?',
        options: ['href="phone:..."', 'href="tel:..."', 'href="call:..."', 'href="dial:..."'],
        correctAnswer: 1,
        explanation: 'tel: é o protocolo para links de telefone',
        points: 10,
    },
    {
        id: 'link-6',
        type: 'multiple-choice',
        question: 'Para que serve rel="noopener"?',
        options: ['Abre mais rápido', 'Segurança', 'Estilo', 'SEO'],
        correctAnswer: 1,
        explanation: 'rel="noopener" previne ataques de segurança em links _blank',
        points: 15,
    },
];

export const BASICS_IMAGES_QUESTIONS: QuizQuestion[] = [
    {
        id: 'img-1',
        type: 'multiple-choice',
        question: 'Para que serve o atributo alt em imagens?',
        options: ['Define a altura', 'Texto alternativo', 'Alinha a imagem', 'Define o formato'],
        correctAnswer: 1,
        explanation: 'alt é o texto alternativo, usado para acessibilidade e quando a imagem não carrega',
        points: 10,
    },
    {
        id: 'img-2',
        type: 'multiple-choice',
        question: 'Qual formato é melhor para fotos?',
        options: ['PNG', 'GIF', 'JPEG', 'SVG'],
        correctAnswer: 2,
        explanation: 'JPEG é otimizado para fotos com muitas cores',
        points: 10,
    },
    {
        id: 'img-3',
        type: 'multiple-choice',
        question: 'Qual formato suporta transparência?',
        options: ['JPEG', 'PNG', 'BMP', 'Todos'],
        correctAnswer: 1,
        explanation: 'PNG suporta transparência (canal alpha)',
        points: 10,
    },
    {
        id: 'img-4',
        type: 'multiple-choice',
        question: 'A tag <img> precisa de fechamento?',
        options: ['Sim, sempre', 'Não, é vazia', 'Depende', 'Opcional'],
        correctAnswer: 1,
        explanation: '<img> é uma tag vazia e não precisa de fechamento',
        points: 10,
    },
    {
        id: 'img-5',
        type: 'multiple-choice',
        question: 'Qual atributo define a largura da imagem?',
        options: ['size', 'width', 'w', 'length'],
        correctAnswer: 1,
        explanation: 'width define a largura em pixels',
        points: 10,
    },
];

export const STRUCTURE_LISTS_QUESTIONS: QuizQuestion[] = [
    {
        id: 'list-1',
        type: 'multiple-choice',
        question: 'Qual tag cria uma lista ordenada?',
        options: ['<ul>', '<ol>', '<li>', '<list>'],
        correctAnswer: 1,
        explanation: '<ol> (ordered list) cria listas numeradas',
        points: 10,
    },
    {
        id: 'list-2',
        type: 'multiple-choice',
        question: 'Qual tag define um item de lista?',
        options: ['<item>', '<li>', '<list-item>', '<it>'],
        correctAnswer: 1,
        explanation: '<li> (list item) define cada item da lista',
        points: 10,
    },
    {
        id: 'list-3',
        type: 'multiple-choice',
        question: 'Como criar lista com marcadores?',
        options: ['<ol>', '<ul>', '<bl>', '<markers>'],
        correctAnswer: 1,
        explanation: '<ul> (unordered list) cria listas com marcadores',
        points: 10,
    },
    {
        id: 'list-4',
        type: 'multiple-choice',
        question: 'Para que serve <dl>?',
        options: ['Lista dupla', 'Lista de definição', 'Lista dinâmica', 'Lista longa'],
        correctAnswer: 1,
        explanation: '<dl> (definition list) para termos e suas definições',
        points: 10,
    },
    {
        id: 'list-5',
        type: 'multiple-choice',
        question: 'Qual a tag do termo em <dl>?',
        options: ['<dt>', '<dd>', '<term>', '<df>'],
        correctAnswer: 0,
        explanation: '<dt> (definition term) define o termo',
        points: 10,
    },
];

export const STRUCTURE_TABLES_QUESTIONS: QuizQuestion[] = [
    {
        id: 'table-1',
        type: 'multiple-choice',
        question: 'Qual tag define uma célula de cabeçalho?',
        options: ['<td>', '<th>', '<tr>', '<thead>'],
        correctAnswer: 1,
        explanation: '<th> (table header) define células de cabeçalho',
        points: 10,
    },
    {
        id: 'table-2',
        type: 'multiple-choice',
        question: 'Qual tag define uma linha da tabela?',
        options: ['<td>', '<th>', '<tr>', '<tl>'],
        correctAnswer: 2,
        explanation: '<tr> (table row) define uma linha',
        points: 10,
    },
    {
        id: 'table-3',
        type: 'multiple-choice',
        question: 'Qual atributo mescla colunas?',
        options: ['rowspan', 'colspan', 'merge', 'span'],
        correctAnswer: 1,
        explanation: 'colspan="n" mescla n colunas',
        points: 10,
    },
    {
        id: 'table-4',
        type: 'multiple-choice',
        question: 'Onde vai o cabeçalho da tabela?',
        options: ['<tbody>', '<thead>', '<tfoot>', '<header>'],
        correctAnswer: 1,
        explanation: '<thead> agrupa as linhas de cabeçalho',
        points: 10,
    },
    {
        id: 'table-5',
        type: 'multiple-choice',
        question: 'Qual tag define uma célula normal?',
        options: ['<tc>', '<td>', '<cell>', '<data>'],
        correctAnswer: 1,
        explanation: '<td> (table data) define células de dados',
        points: 10,
    },
];

export const STRUCTURE_DIVSPAN_QUESTIONS: QuizQuestion[] = [
    {
        id: 'div-1',
        type: 'multiple-choice',
        question: 'Qual é a diferença entre div e span?',
        options: ['div é inline, span é bloco', 'div é bloco, span é inline', 'São iguais', 'Nenhuma diferença'],
        correctAnswer: 1,
        explanation: '<div> é elemento de bloco, <span> é inline',
        points: 10,
    },
    {
        id: 'div-2',
        type: 'multiple-choice',
        question: 'Para que serve <div>?',
        options: ['Dividir texto', 'Agrupar elementos', 'Criar divisões', 'Todas anteriores'],
        correctAnswer: 1,
        explanation: '<div> agrupa elementos para estilização ou layout',
        points: 10,
    },
    {
        id: 'div-3',
        type: 'multiple-choice',
        question: 'Quando usar <span>?',
        options: ['Estilizar parte do texto', 'Criar seções', 'Fazer layout', 'Agrupar blocos'],
        correctAnswer: 0,
        explanation: '<span> é usado para estilizar partes do texto inline',
        points: 10,
    },
    {
        id: 'div-4',
        type: 'multiple-choice',
        question: '<div> ocupa quantas colunas por padrão?',
        options: ['Metade', '100%', 'Auto', 'Depende'],
        correctAnswer: 1,
        explanation: '<div> é block-level e ocupa 100% da largura disponível',
        points: 10,
    },
    {
        id: 'div-5',
        type: 'multiple-choice',
        question: '<span> quebra linha?',
        options: ['Sim', 'Não', 'Às vezes', 'Depende do CSS'],
        correctAnswer: 1,
        explanation: '<span> é inline e não quebra linha por padrão',
        points: 10,
    },
];

export const STRUCTURE_CLASSID_QUESTIONS: QuizQuestion[] = [
    {
        id: 'classid-1',
        type: 'multiple-choice',
        question: 'Quantas vezes um ID pode aparecer na página?',
        options: ['Quantas quiser', 'Apenas 1', 'Máximo 3', 'Depende'],
        correctAnswer: 1,
        explanation: 'IDs devem ser únicos na página',
        points: 10,
    },
    {
        id: 'classid-2',
        type: 'multiple-choice',
        question: 'Como aplicar múltiplas classes?',
        options: ['class="a,b"', 'class="a b"', 'class="a+b"', 'class=["a","b"]'],
        correctAnswer: 1,
        explanation: 'Classes são separadas por espaço: class="classe1 classe2"',
        points: 10,
    },
    {
        id: 'classid-3',
        type: 'multiple-choice',
        question: 'Qual seletor CSS para ID?',
        options: ['.id', '#id', '@id', '&id'],
        correctAnswer: 1,
        explanation: '# é o seletor de ID no CSS',
        points: 10,
    },
    {
        id: 'classid-4',
        type: 'multiple-choice',
        question: 'Qual seletor CSS para class?',
        options: ['.classe', '#classe', '@classe', '$classe'],
        correctAnswer: 0,
        explanation: '. (ponto) é o seletor de classe no CSS',
        points: 10,
    },
    {
        id: 'classid-5',
        type: 'multiple-choice',
        question: 'Classes podem ser reutilizadas?',
        options: ['Não', 'Sim', 'Apenas 2 vezes', 'Apenas em divs'],
        correctAnswer: 1,
        explanation: 'Classes podem e devem ser reutilizadas em múltiplos elementos',
        points: 10,
    },
];
