// CodeQuest - Expanded Questions (Part 3: Forms & Semantics)
import type { QuizQuestion } from './lessons';

export const FORMS_BASICS_QUESTIONS: QuizQuestion[] = [
    {
        id: 'form-1',
        type: 'multiple-choice',
        question: 'Qual atributo conecta um label ao seu input?',
        options: ['name', 'id', 'for', 'href'],
        correctAnswer: 2,
        explanation: 'O atributo for do label deve ter o mesmo valor que o id do input',
        points: 10,
    },
    {
        id: 'form-2',
        type: 'multiple-choice',
        question: 'Qual método envia dados de forma visível na URL?',
        options: ['POST', 'GET', 'PUT', 'SEND'],
        correctAnswer: 1,
        explanation: 'GET envia dados na URL, POST envia no corpo da requisição',
        points: 10,
    },
    {
        id: 'form-3',
        type: 'multiple-choice',
        question: 'Para que serve o atributo action?',
        options: ['Define o estilo', 'URL de destino', 'Tipo de dado', 'Validação'],
        correctAnswer: 1,
        explanation: 'action define para onde os dados serão enviados',
        points: 10,
    },
    {
        id: 'form-4',
        type: 'multiple-choice',
        question: 'Qual botão envia o formulário?',
        options: ['type="button"', 'type="submit"', 'type="send"', 'type="form"'],
        correctAnswer: 1,
        explanation: 'type="submit" envia o formulário',
        points: 10,
    },
    {
        id: 'form-5',
        type: 'multiple-choice',
        question: 'Para que serve <fieldset>?',
        options: ['Agrupar campos', 'Estilizar form', 'Validar dados', 'Enviar form'],
        correctAnswer: 0,
        explanation: '<fieldset> agrupa campos relacionados semanticamente',
        points: 10,
    },
];

export const FORMS_INPUTS_QUESTIONS: QuizQuestion[] = [
    {
        id: 'input-1',
        type: 'multiple-choice',
        question: 'Qual tipo de input valida email automaticamente?',
        options: ['type="text"', 'type="email"', 'type="mail"', 'validate="email"'],
        correctAnswer: 1,
        explanation: 'type="email" valida formato de email nativamente',
        points: 10,
    },
    {
        id: 'input-2',
        type: 'multiple-choice',
        question: 'Qual input cria campo de senha?',
        options: ['type="hidden"', 'type="secret"', 'type="password"', 'type="private"'],
        correctAnswer: 2,
        explanation: 'type="password" oculta os caracteres digitados',
        points: 10,
    },
    {
        id: 'input-3',
        type: 'multiple-choice',
        question: 'Qual input cria um slider?',
        options: ['type="slider"', 'type="range"', 'type="slide"', 'type="bar"'],
        correctAnswer: 1,
        explanation: 'type="range" cria um controle deslizante',
        points: 10,
    },
    {
        id: 'input-4',
        type: 'multiple-choice',
        question: 'Como selecionar uma cor?',
        options: ['type="rgb"', 'type="palette"', 'type="color"', 'type="picker"'],
        correctAnswer: 2,
        explanation: 'type="color" abre um seletor de cores',
        points: 10,
    },
    {
        id: 'input-5',
        type: 'multiple-choice',
        question: 'Checkboxes usam qual atributo para agrupar?',
        options: ['group', 'name', 'id', 'set'],
        correctAnswer: 1,
        explanation: 'name agrupa checkboxes relacionados',
        points: 10,
    },
];

export const FORMS_VALIDATION_QUESTIONS: QuizQuestion[] = [
    {
        id: 'valid-1',
        type: 'multiple-choice',
        question: 'Qual atributo torna um campo obrigatório?',
        options: ['mandatory', 'required', 'must', 'needed'],
        correctAnswer: 1,
        explanation: 'required impede envio sem preencher o campo',
        points: 10,
    },
    {
        id: 'valid-2',
        type: 'multiple-choice',
        question: 'Qual atributo limita o tamanho mínimo?',
        options: ['min-length', 'minlength', 'minsize', 'min'],
        correctAnswer: 1,
        explanation: 'minlength define quantidade mínima de caracteres',
        points: 10,
    },
    {
        id: 'valid-3',
        type: 'multiple-choice',
        question: 'Qual atributo define um padrão de validação?',
        options: ['regex', 'pattern', 'validate', 'format'],
        correctAnswer: 1,
        explanation: 'pattern aceita expressões regulares para validação',
        points: 10,
    },
    {
        id: 'valid-4',
        type: 'multiple-choice',
        question: 'Qual atributo define valor máximo para números?',
        options: ['maximum', 'maxvalue', 'max', 'limit'],
        correctAnswer: 2,
        explanation: 'max define o valor máximo permitido',
        points: 10,
    },
    {
        id: 'valid-5',
        type: 'multiple-choice',
        question: 'placeholder é validação?',
        options: ['Sim', 'Não', 'Às vezes', 'Depende'],
        correctAnswer: 1,
        explanation: 'placeholder é apenas dica visual, não valida',
        points: 10,
    },
];

export const SEMANTICS_ELEMENTS_QUESTIONS: QuizQuestion[] = [
    {
        id: 'sem-1',
        type: 'multiple-choice',
        question: 'Qual tag define o conteúdo principal?',
        options: ['<content>', '<main>', '<body>', '<article>'],
        correctAnswer: 1,
        explanation: '<main> define o conteúdo principal único da página',
        points: 10,
    },
    {
        id: 'sem-2',
        type: 'multiple-choice',
        question: 'Qual tag é para navegação?',
        options: ['<menu>', '<nav>', '<links>', '<navigation>'],
        correctAnswer: 1,
        explanation: '<nav> define área de navegação',
        points: 10,
    },
    {
        id: 'sem-3',
        type: 'multiple-choice',
        question: 'Qual tag é para conteúdo independente?',
        options: ['<section>', '<article>', '<div>', '<content>'],
        correctAnswer: 1,
        explanation: '<article> para conteúdo que faz sentido sozinho',
        points: 10,
    },
    {
        id: 'sem-4',
        type: 'multiple-choice',
        question: 'Qual tag é para conteúdo relacionado lateralmente?',
        options: ['<sidebar>', '<aside>', '<side>', '<related>'],
        correctAnswer: 1,
        explanation: '<aside> para conteúdo tangencialmente relacionado',
        points: 10,
    },
    {
        id: 'sem-5',
        type: 'multiple-choice',
        question: 'Quantos <main> devem ter por página?',
        options: ['Quantos quiser', 'Apenas 1', 'Máximo 2', 'Nenhum'],
        correctAnswer: 1,
        explanation: 'Deve haver apenas um <main> por página',
        points: 10,
    },
];

export const SEMANTICS_ACCESSIBILITY_QUESTIONS: QuizQuestion[] = [
    {
        id: 'a11y-1',
        type: 'multiple-choice',
        question: 'O que significa alt="" em uma imagem decorativa?',
        options: ['Erro', 'Imagem sem descrição', 'Ignorar imagem', 'Texto vazio'],
        correctAnswer: 2,
        explanation: 'alt="" indica que a imagem é decorativa e pode ser ignorada',
        points: 15,
    },
    {
        id: 'a11y-2',
        type: 'multiple-choice',
        question: 'O que é ARIA?',
        options: ['Navegador', 'Frameworks', 'Acessibilidade', 'Animação'],
        correctAnswer: 2,
        explanation: 'ARIA = Accessible Rich Internet Applications',
        points: 10,
    },
    {
        id: 'a11y-3',
        type: 'multiple-choice',
        question: 'Qual atributo torna elemento focável por Tab?',
        options: ['focus', 'tabindex', 'tab', 'focusable'],
        correctAnswer: 1,
        explanation: 'tabindex torna elementos focáveis pelo teclado',
        points: 10,
    },
    {
        id: 'a11y-4',
        type: 'multiple-choice',
        question: 'Para que serve aria-label?',
        options: ['Estilo', 'Descrição acessível', 'ID', 'Class'],
        correctAnswer: 1,
        explanation: 'aria-label fornece descrição para leitores de tela',
        points: 10,
    },
    {
        id: 'a11y-5',
        type: 'multiple-choice',
        question: 'role="button" serve para quê?',
        options: ['Estilo de botão', 'Tipo de botão', 'Indicar que é botão', 'Nada'],
        correctAnswer: 2,
        explanation: 'role indica o papel do elemento para tecnologias assistivas',
        points: 10,
    },
];
